export const CURRENCY_NAMES_AR: Record<string, { ar: string; symbol: string }> =
  {
    // ── Major ────────────────────────────────────────────────────────────────
    USD: { ar: "دولار أمريكي", symbol: "$" },
    EUR: { ar: "يورو", symbol: "€" },
    GBP: { ar: "جنيه إسترليني", symbol: "£" },
    JPY: { ar: "ين ياباني", symbol: "¥" },
    CHF: { ar: "فرنك سويسري", symbol: "Fr" },
    CNY: { ar: "يوان صيني", symbol: "¥" },
    CNH: { ar: "يوان صيني (خارجي)", symbol: "¥" },
    CAD: { ar: "دولار كندي", symbol: "C$" },
    AUD: { ar: "دولار أسترالي", symbol: "A$" },
    NZD: { ar: "دولار نيوزيلندي", symbol: "NZ$" },
    HKD: { ar: "دولار هونج كونج", symbol: "HK$" },
    SGD: { ar: "دولار سنغافوري", symbol: "S$" },
    KRW: { ar: "وون كوري", symbol: "₩" },
    INR: { ar: "روبية هندية", symbol: "₹" },
    BRL: { ar: "ريال برازيلي", symbol: "R$" },
    MXN: { ar: "بيزو مكسيكي", symbol: "$" },
    SEK: { ar: "كرون سويدي", symbol: "kr" },
    NOK: { ar: "كرون نرويجي", symbol: "kr" },
    DKK: { ar: "كرون دنماركي", symbol: "kr" },
    PLN: { ar: "زلوتي بولندي", symbol: "zł" },
    CZK: { ar: "كورونا تشيكية", symbol: "Kč" },
    HUF: { ar: "فورنت مجري", symbol: "Ft" },
    RON: { ar: "ليو روماني", symbol: "lei" },
    HRK: { ar: "كونا كرواتي", symbol: "kn" },
    BGN: { ar: "ليف بلغاري", symbol: "лв" },
    RUB: { ar: "روبل روسي", symbol: "₽" },
    TRY: { ar: "ليرة تركية", symbol: "₺" },
    ZAR: { ar: "راند جنوب أفريقي", symbol: "R" },
    MYR: { ar: "رينغيت ماليزي", symbol: "RM" },
    THB: { ar: "بات تايلاندي", symbol: "฿" },
    IDR: { ar: "روبية إندونيسية", symbol: "Rp" },
    PKR: { ar: "روبية باكستانية", symbol: "₨" },

    // ── Arab & Middle East ───────────────────────────────────────────────────
    EGP: { ar: "جنيه مصري", symbol: "ج.م" },
    SAR: { ar: "ريال سعودي", symbol: "ر.س" },
    AED: { ar: "درهم إماراتي", symbol: "د.إ" },
    KWD: { ar: "دينار كويتي", symbol: "د.ك" },
    QAR: { ar: "ريال قطري", symbol: "ر.ق" },
    BHD: { ar: "دينار بحريني", symbol: "د.ب" },
    OMR: { ar: "ريال عماني", symbol: "ر.ع" },
    JOD: { ar: "دينار أردني", symbol: "د.أ" },
    LBP: { ar: "ليرة لبنانية", symbol: "ل.ل" },
    IQD: { ar: "دينار عراقي", symbol: "د.ع" },
    LYD: { ar: "دينار ليبي", symbol: "د.ل" },
    TND: { ar: "دينار تونسي", symbol: "د.ت" },
    MAD: { ar: "درهم مغربي", symbol: "د.م" },
    DZD: { ar: "دينار جزائري", symbol: "د.ج" },
    SDG: { ar: "جنيه سوداني", symbol: "ج.س" },
    SYP: { ar: "ليرة سورية", symbol: "ل.س" },
    YER: { ar: "ريال يمني", symbol: "ر.ي" },
    IRR: { ar: "ريال إيراني", symbol: "﷼" },

    // ── Africa ───────────────────────────────────────────────────────────────
    NGN: { ar: "نيرا نيجيري", symbol: "₦" },
    KES: { ar: "شلن كيني", symbol: "KSh" },
    GHS: { ar: "سيدي غاني", symbol: "₵" },
    ETB: { ar: "بر إثيوبي", symbol: "Br" },
    TZS: { ar: "شلن تنزاني", symbol: "TSh" },
    UGX: { ar: "شلن أوغندي", symbol: "USh" },
    ZMW: { ar: "كواشا زامبي", symbol: "ZK" },
    RWF: { ar: "فرنك رواندي", symbol: "Fr" },
    MWK: { ar: "كواشا مالاوي", symbol: "MK" },
    MZN: { ar: "ميتيكال موزمبيقي", symbol: "MT" },
    MGA: { ar: "أرياري مدغشقري", symbol: "Ar" },
    MUR: { ar: "روبية موريشيوسية", symbol: "₨" },
    SCR: { ar: "روبية سيشيلية", symbol: "₨" },
    GMD: { ar: "دالاسي غامبي", symbol: "D" },
    GNF: { ar: "فرنك غيني", symbol: "Fr" },
    SLE: { ar: "ليون سيراليوني", symbol: "Le" },
    SLL: { ar: "ليون سيراليوني (قديم)", symbol: "Le" },
    CVE: { ar: "إيسكودو رأس الأخضر", symbol: "Esc" },
    STN: { ar: "دوبرا ساو تومي", symbol: "Db" },
    XAF: { ar: "فرنك وسط أفريقي", symbol: "Fr" },
    XOF: { ar: "فرنك غرب أفريقي", symbol: "Fr" },
    XPF: { ar: "فرنك المحيط الهادئ", symbol: "Fr" },
    LSL: { ar: "لوتي ليسوتي", symbol: "L" },
    SZL: { ar: "ليلانجيني سوازيلاندي", symbol: "L" },
    NAD: { ar: "دولار ناميبي", symbol: "N$" },
    BWP: { ar: "بولا بوتسواني", symbol: "P" },
    LRD: { ar: "دولار ليبيري", symbol: "L$" },
    DJF: { ar: "فرنك جيبوتي", symbol: "Fr" },
    KMF: { ar: "فرنك جزر القمر", symbol: "Fr" },
    ERN: { ar: "ناكفا إريتري", symbol: "Nkf" },
    SSP: { ar: "جنيه جنوب سوداني", symbol: "£" },
    SOS: { ar: "شلن صومالي", symbol: "Sh" },
    MDL: { ar: "ليو مولدوفي", symbol: "L" },

    // ── Asia Pacific ─────────────────────────────────────────────────────────
    PHP: { ar: "بيزو فلبيني", symbol: "₱" },
    VND: { ar: "دونغ فيتنامي", symbol: "₫" },
    BDT: { ar: "تاكا بنغلاديشي", symbol: "৳" },
    LKR: { ar: "روبية سريلانكية", symbol: "₨" },
    NPR: { ar: "روبية نيبالية", symbol: "₨" },
    MMK: { ar: "كيات ميانماري", symbol: "K" },
    KHR: { ar: "رييل كمبودي", symbol: "៛" },
    LAK: { ar: "كيب لاوسي", symbol: "₭" },
    TWD: { ar: "دولار تايواني", symbol: "NT$" },
    MNT: { ar: "توغروغ منغولي", symbol: "₮" },
    KGS: { ar: "سوم قيرغيزي", symbol: "с" },
    KZT: { ar: "تنغي كازاخستاني", symbol: "₸" },
    UZS: { ar: "سوم أوزبكي", symbol: "soʻm" },
    TJS: { ar: "سوموني طاجيكي", symbol: "SM" },
    TMT: { ar: "مانات تركماني", symbol: "T" },
    AZN: { ar: "مانات أذربيجاني", symbol: "₼" },
    GEL: { ar: "لاري جورجي", symbol: "₾" },
    AMD: { ar: "درام أرمني", symbol: "֏" },
    ISK: { ar: "كرونة إيسلندية", symbol: "kr" },
    MOP: { ar: "باتاكا ماكاوي", symbol: "P" },
    BND: { ar: "دولار بروناي", symbol: "B$" },
    BTN: { ar: "نغولتروم بوتاني", symbol: "Nu" },
    MVR: { ar: "روفية مالديفية", symbol: "Rf" },
    MRU: { ar: "أوقية موريتانية", symbol: "UM" },
    KID: { ar: "دولار جزر كيريباتي", symbol: "$" },
    TVD: { ar: "دولار توفالو", symbol: "$" },

    // ── Americas ─────────────────────────────────────────────────────────────
    ARS: { ar: "بيزو أرجنتيني", symbol: "$" },
    CLP: { ar: "بيزو تشيلي", symbol: "$" },
    CLF: { ar: "وحدة تشيلية (UF)", symbol: "UF" },
    COP: { ar: "بيزو كولومبي", symbol: "$" },
    PEN: { ar: "سول بيروفي", symbol: "S/" },
    UYU: { ar: "بيزو أوروغواياني", symbol: "$U" },
    BOB: { ar: "بوليفيانو بوليفي", symbol: "Bs" },
    PYG: { ar: "غواراني باراغواياني", symbol: "₲" },
    GTQ: { ar: "كيتزال غواتيمالي", symbol: "Q" },
    HNL: { ar: "ليمبيرا هندوراسي", symbol: "L" },
    NIO: { ar: "كوردوبا نيكاراغوي", symbol: "C$" },
    CRC: { ar: "كولون كوستاريكي", symbol: "₡" },
    DOP: { ar: "بيزو دومينيكاني", symbol: "RD$" },
    JMD: { ar: "دولار جامايكي", symbol: "J$" },
    TTD: { ar: "دولار ترينيداد", symbol: "TT$" },
    BBD: { ar: "دولار باربادوسي", symbol: "Bds$" },
    BSD: { ar: "دولار باهامي", symbol: "B$" },
    BZD: { ar: "دولار بليزي", symbol: "BZ$" },
    PAB: { ar: "بالبوا بنمي", symbol: "B/." },
    KYD: { ar: "دولار جزر كايمان", symbol: "CI$" },
    XCD: { ar: "دولار شرق الكاريبي", symbol: "EC$" },
    GYD: { ar: "دولار غياني", symbol: "G$" },
    SRD: { ar: "دولار سورينامي", symbol: "$" },
    AWG: { ar: "فلورين أروباني", symbol: "Afl" },
    ANG: { ar: "غيلدر أنتيلي", symbol: "ƒ" },
    CUP: { ar: "بيزو كوبي", symbol: "$" },
    VES: { ar: "بوليفار فنزويلي", symbol: "Bs.S" },
    HTG: { ar: "غورد هايتي", symbol: "G" },

    // ── Europe (others) ──────────────────────────────────────────────────────
    MKD: { ar: "دينار مقدوني", symbol: "ден" },
    RSD: { ar: "دينار صربي", symbol: "din" },
    BAM: { ar: "مارك بوسني", symbol: "KM" },
    ALL: { ar: "ليك ألباني", symbol: "L" },
    BYN: { ar: "روبل بيلاروسي", symbol: "Br" },
    UAH: { ar: "هريفنيا أوكراني", symbol: "₴" },

    // ── Pacific ──────────────────────────────────────────────────────────────
    FJD: { ar: "دولار فيجي", symbol: "FJ$" },
    PGK: { ar: "كينا بابوا غينيا", symbol: "K" },
    WST: { ar: "تالا ساموي", symbol: "WS$" },
    VUV: { ar: "واتو فانواتو", symbol: "VT" },
    TOP: { ar: "باآنغا تونغي", symbol: "T$" },
    SBD: { ar: "دولار جزر سليمان", symbol: "SI$" },
    FOK: { ar: "كرونة فارو", symbol: "kr" },

    // ── Special / Territories ────────────────────────────────────────────────
    BMD: { ar: "دولار برمودي", symbol: "$" },
    FKP: { ar: "جنيه فوكلاند", symbol: "£" },
    GIP: { ar: "جنيه جبل طارق", symbol: "£" },
    SHP: { ar: "جنيه سانت هيلينا", symbol: "£" },
    IMP: { ar: "جنيه جزيرة مان", symbol: "£" },
    JEP: { ar: "جنيه جيرسي", symbol: "£" },
    GGP: { ar: "جنيه غيرنسي", symbol: "£" },
    XDR: { ar: "حقوق السحب الخاصة", symbol: "SDR" },
    XCG: { ar: "غيلدر الكاريبي", symbol: "ƒ" },
    ZWG: { ar: "دولار زيمبابوي", symbol: "ZiG" },
    ZWL: { ar: "دولار زيمبابوي (قديم)", symbol: "$" },
  };
