export const ETF_LIST = [
  // Egypt
  {
    id: "1",
    ticker: "^CASE30",
    yahooTicker: "^CASE30",
    titleAr: "مؤشر EGX30",
    titleEn: "EGX 30 Index",
    slug: "egx30",
    currency: "EGP",
    market: "EGX" as const,
    category: "egypt" as const,
  },
  {
    id: "2",
    ticker: "^EGX70EWI.CA",
    yahooTicker: "^EGX70EWI.CA",
    titleAr: "مؤشر EGX70",
    titleEn: "EGX 70 Index",
    slug: "egx70",
    currency: "EGP",
    market: "EGX" as const,
    category: "egypt" as const,
  },
  {
    id: "3",
    ticker: "^EGX100EWI.CA",
    yahooTicker: "^EGX100EWI.CA",
    titleAr: "مؤشر EGX100",
    titleEn: "EGX 100 Index",
    slug: "egx100",
    currency: "EGP",
    market: "EGX" as const,
    category: "egypt" as const,
  },
  {
    id: "4",
    ticker: "EGPT",
    yahooTicker: "EGPT",
    titleAr: "فانيك مصر",
    titleEn: "VanEck Egypt ETF",
    slug: "egpt",
    currency: "USD",
    market: "US" as const,
    category: "egypt" as const,
  },
  // Global
  {
    id: "5",
    ticker: "SPY",
    yahooTicker: "SPY",
    titleAr: "S&P 500",
    titleEn: "SPDR S&P 500 ETF",
    slug: "spy",
    currency: "USD",
    market: "US" as const,
    category: "global" as const,
  },
  {
    id: "6",
    ticker: "QQQ",
    yahooTicker: "QQQ",
    titleAr: "ناسداك 100",
    titleEn: "Invesco QQQ Trust",
    slug: "qqq",
    currency: "USD",
    market: "US" as const,
    category: "global" as const,
  },
  {
    id: "7",
    ticker: "VTI",
    yahooTicker: "VTI",
    titleAr: "السوق الأمريكي الكلي",
    titleEn: "Vanguard Total Market ETF",
    slug: "vti",
    currency: "USD",
    market: "US" as const,
    category: "global" as const,
  },
  {
    id: "8",
    ticker: "IWM",
    yahooTicker: "IWM",
    titleAr: "راسل 2000",
    titleEn: "iShares Russell 2000 ETF",
    slug: "iwm",
    currency: "USD",
    market: "US" as const,
    category: "global" as const,
  },
  {
    id: "9",
    ticker: "EEM",
    yahooTicker: "EEM",
    titleAr: "الأسواق الناشئة",
    titleEn: "iShares MSCI Emerging",
    slug: "eem",
    currency: "USD",
    market: "US" as const,
    category: "global" as const,
  },
  {
    id: "10",
    ticker: "ACWI",
    yahooTicker: "ACWI",
    titleAr: "الأسهم العالمية",
    titleEn: "iShares MSCI ACWI ETF",
    slug: "acwi",
    currency: "USD",
    market: "US" as const,
    category: "global" as const,
  },
  // Sector
  {
    id: "11",
    ticker: "XLK",
    yahooTicker: "XLK",
    titleAr: "التكنولوجيا",
    titleEn: "Technology Select SPDR",
    slug: "xlk",
    currency: "USD",
    market: "US" as const,
    category: "sector" as const,
  },
  {
    id: "12",
    ticker: "XLF",
    yahooTicker: "XLF",
    titleAr: "المالية",
    titleEn: "Financial Select SPDR",
    slug: "xlf",
    currency: "USD",
    market: "US" as const,
    category: "sector" as const,
  },
  {
    id: "13",
    ticker: "XLE",
    yahooTicker: "XLE",
    titleAr: "الطاقة",
    titleEn: "Energy Select SPDR",
    slug: "xle",
    currency: "USD",
    market: "US" as const,
    category: "sector" as const,
  },
  {
    id: "14",
    ticker: "XLV",
    yahooTicker: "XLV",
    titleAr: "الرعاية الصحية",
    titleEn: "Health Care Select SPDR",
    slug: "xlv",
    currency: "USD",
    market: "US" as const,
    category: "sector" as const,
  },
  {
    id: "15",
    ticker: "ARKK",
    yahooTicker: "ARKK",
    titleAr: "آرك للابتكار",
    titleEn: "ARK Innovation ETF",
    slug: "arkk",
    currency: "USD",
    market: "US" as const,
    category: "sector" as const,
  },
  // Commodities
  {
    id: "16",
    ticker: "GLD",
    yahooTicker: "GLD",
    titleAr: "الذهب",
    titleEn: "SPDR Gold Shares",
    slug: "gld",
    currency: "USD",
    market: "US" as const,
    category: "commodities" as const,
  },
  {
    id: "17",
    ticker: "SLV",
    yahooTicker: "SLV",
    titleAr: "الفضة",
    titleEn: "iShares Silver Trust",
    slug: "slv",
    currency: "USD",
    market: "US" as const,
    category: "commodities" as const,
  },
  {
    id: "18",
    ticker: "USO",
    yahooTicker: "USO",
    titleAr: "النفط الخام",
    titleEn: "US Oil Fund ETF",
    slug: "uso",
    currency: "USD",
    market: "US" as const,
    category: "commodities" as const,
  },
  // Bonds
  {
    id: "19",
    ticker: "TLT",
    yahooTicker: "TLT",
    titleAr: "السندات طويلة الأجل",
    titleEn: "iShares 20+ Year Treasury",
    slug: "tlt",
    currency: "USD",
    market: "US" as const,
    category: "bonds" as const,
  },
  {
    id: "20",
    ticker: "BND",
    yahooTicker: "BND",
    titleAr: "السندات الأمريكية",
    titleEn: "Vanguard Total Bond Market",
    slug: "bnd",
    currency: "USD",
    market: "US" as const,
    category: "bonds" as const,
  },
  {
    id: "21",
    ticker: "EMB",
    yahooTicker: "EMB",
    titleAr: "سندات الأسواق الناشئة",
    titleEn: "iShares JP Morgan EM Bond",
    slug: "emb",
    currency: "USD",
    market: "US" as const,
    category: "bonds" as const,
  },
  // Arab
  {
    id: "22",
    ticker: "KSA",
    yahooTicker: "KSA",
    titleAr: "السوق السعودي",
    titleEn: "iShares MSCI Saudi Arabia",
    slug: "ksa",
    currency: "USD",
    market: "US" as const,
    category: "arab" as const,
  },
  {
    id: "23",
    ticker: "UAE",
    yahooTicker: "UAE",
    titleAr: "السوق الإماراتي",
    titleEn: "iShares MSCI UAE ETF",
    slug: "uae",
    currency: "USD",
    market: "US" as const,
    category: "arab" as const,
  },
  {
    id: "24",
    ticker: "QAT",
    yahooTicker: "QAT",
    titleAr: "السوق القطري",
    titleEn: "iShares MSCI Qatar ETF",
    slug: "qat",
    currency: "USD",
    market: "US" as const,
    category: "arab" as const,
  },
  {
    id: "25",
    ticker: "GULF",
    yahooTicker: "GULF",
    titleAr: "منطقة الخليج",
    titleEn: "WisdomTree Middle East",
    slug: "gulf",
    currency: "USD",
    market: "US" as const,
    category: "arab" as const,
  },
];