export const EGX_STOCKS = [
  // ── BANKING ───────────────────────────────────────────────────────────────
  {
    code: "COMI",
    yahooCode: "EGS60121C018.CA",
    titleAr: "البنك التجاري الدولي",
    titleEn: "Commercial International Bank (CIB)",
    sector: "بنوك",
  },
  {
    code: "HDBK",
    yahooCode: "EGS60301C016.CA",
    titleAr: "بنك الإسكان والتعمير",
    titleEn: "Housing & Development Bank",
    sector: "بنوك",
  },
  {
    code: "ADIB",
    yahooCode: "EGS60111C019.CA",
    titleAr: "بنك أبوظبي الإسلامي مصر",
    titleEn: "Abu Dhabi Islamic Bank Egypt",
    sector: "بنوك",
  },
  {
    code: "SAUD",
    yahooCode: "EGS67031C012.CA",
    titleAr: "بنك البركة مصر",
    titleEn: "alBaraka Bank Egypt",
    sector: "بنوك",
  },
  {
    code: "EXPA",
    yahooCode: "EGS60241C014.CA",
    titleAr: "بنك تنمية الصادرات",
    titleEn: "Export Development Bank of Egypt",
    sector: "بنوك",
  },
  {
    code: "CIRE",
    yahooCode: "EGS65541C012.CA",
    titleAr: "القاهرة للاستثمار والتعمير",
    titleEn: "Cairo For Investment And Real Estate",
    sector: "بنوك",
  },

  // ── REAL ESTATE & CONSTRUCTION ────────────────────────────────────────────
  {
    code: "PHDC",
    yahooCode: "EGS655L1C012.CA",
    titleAr: "بالم هيلز للتطوير",
    titleEn: "Palm Hills Developments",
    sector: "عقارات",
  },
  {
    code: "TMGH",
    yahooCode: "EGS691S1C011.CA",
    titleAr: "طلعت مصطفى القابضة",
    titleEn: "Talaat Moustafa Group Holding",
    sector: "عقارات",
  },
  {
    code: "MNHD",
    yahooCode: "EGS65571C019.CA",
    titleAr: "مدينة نصر للإسكان",
    titleEn: "Madinet Nasr Housing",
    sector: "عقارات",
  },
  {
    code: "ORHD",
    yahooCode: "EGS70321C012.CA",
    titleAr: "أوراسكوم للتنمية مصر",
    titleEn: "Orascom Development Egypt",
    sector: "عقارات",
  },
  {
    code: "EMFD",
    yahooCode: "EGS673Y1C015.CA",
    titleAr: "إعمار مصر للتنمية",
    titleEn: "Emaar Misr for Development",
    sector: "عقارات",
  },
  {
    code: "HELI",
    yahooCode: "EGS65591C017.CA",
    titleAr: "مصر الجديدة للإسكان والتعمير",
    titleEn: "Heliopolis Co. for Housing & Development",
    sector: "عقارات",
  },
  {
    code: "EGCH",
    yahooCode: "EGS65341C017.CA",
    titleAr: "القاهرة للإسكان والتعمير",
    titleEn: "Cairo Housing & Development",
    sector: "عقارات",
  },
  {
    code: "OBRI",
    yahooCode: "EGS65551C011.CA",
    titleAr: "العبور للاستثمار العقاري",
    titleEn: "El-Ebour Co. for Real Estate Investment",
    sector: "عقارات",
  },
  {
    code: "GIHD",
    yahooCode: "EGS21541C015.CA",
    titleAr: "الغربية الإسلامية للإسكان",
    titleEn: "Gharbia Islamic Housing Development",
    sector: "عقارات",
  },
  {
    code: "ORWE",
    yahooCode: "EGS95001C011.CA",
    titleAr: "الشركة الشرقية للسجاد",
    titleEn: "Oriental Weavers Carpets",
    sector: "صناعة",
  },

  // ── TELECOM & TECHNOLOGY ──────────────────────────────────────────────────
  {
    code: "ETEL",
    yahooCode: "EGS48031C016.CA",
    titleAr: "المصرية للاتصالات",
    titleEn: "Telecom Egypt",
    sector: "اتصالات",
  },
  {
    code: "FWRY",
    yahooCode: "EGS745L1C014.CA",
    titleAr: "فوري للتكنولوجيا المصرفية",
    titleEn: "Fawry for Banking Technology",
    sector: "تكنولوجيا",
  },
  {
    code: "ETRS",
    yahooCode: "EGS42051C010.CA",
    titleAr: "الشركة المصرية لخدمات النقل",
    titleEn: "Egyptian Transport and Commercial Services",
    sector: "نقل",
  },
  {
    code: "APSW",
    yahooCode: "EGS42111C012.CA",
    titleAr: "الإسكندرية لخدمات الموانئ",
    titleEn: "Alexandria Port Container Services",
    sector: "نقل",
  },
  {
    code: "ELEC",
    yahooCode: "EGS3G231C011.CA",
    titleAr: "كابلات الكهرباء المصرية",
    titleEn: "Electro Cable Egypt",
    sector: "صناعة",
  },
  {
    code: "EEII",
    yahooCode: "EGS3G111C015.CA",
    titleAr: "العربية للصناعات الهندسية",
    titleEn: "Arab Engineering Industries",
    sector: "صناعة",
  },

  // ── ENERGY & INDUSTRIALS ──────────────────────────────────────────────────
  {
    code: "ALCN",
    yahooCode: "EGS01071C017.CA",
    titleAr: "الإسكندرية للحاويات",
    titleEn: "Alexandria Container & Cargo Handling",
    sector: "نقل",
  },
  {
    code: "ATQA",
    yahooCode: "EGS3D0C1C018.CA",
    titleAr: "حديد مصر الوطني - عتاقة",
    titleEn: "Misr National Steel - Ataqa",
    sector: "صناعة",
  },
  {
    code: "ALUM",
    yahooCode: "EGS3E181C010.CA",
    titleAr: "الألومنيوم المصري",
    titleEn: "Egyptian Aluminium",
    sector: "صناعة",
  },

  // ── FERTILIZERS & CHEMICALS ───────────────────────────────────────────────
  {
    code: "ABUK",
    yahooCode: "EGS38191C010.CA",
    titleAr: "أبوقير للأسمدة والصناعات الكيماوية",
    titleEn: "Abu Qir Fertilizers and Chemical Industries",
    sector: "كيماويات",
  },
  {
    code: "MFPC",
    yahooCode: "EGS39061C014.CA",
    titleAr: "موبكو لإنتاج الأسمدة",
    titleEn: "Misr Fertilizer Production Company (MOPCO)",
    sector: "كيماويات",
  },
  {
    code: "SKPC",
    yahooCode: "EGS380S1C017.CA",
    titleAr: "سيدي كرير للبتروكيماويات",
    titleEn: "Sidi Kerir Petrochemicals",
    sector: "كيماويات",
  },
  {
    code: "KABO",
    yahooCode: "EGS38411C012.CA",
    titleAr: "كفر الزيات للمبيدات والكيماويات",
    titleEn: "Kafr El Zayat For Pesticides & Chemicals",
    sector: "كيماويات",
  },
  {
    code: "MICH",
    yahooCode: "EGS38211C016.CA",
    titleAr: "مصر للصناعات الكيماوية",
    titleEn: "Misr Chemical Industries",
    sector: "كيماويات",
  },
  {
    code: "ZEOT",
    yahooCode: "EGS38251C012.CA",
    titleAr: "الزيوت والمشتقات المستخلصة",
    titleEn: "Extracted Oils & Derivatives",
    sector: "كيماويات",
  },
  {
    code: "EGCH",
    yahooCode: "EGS38201C017.CA",
    titleAr: "الشركة المصرية للكيماويات",
    titleEn: "Egyptian Chemical Industries (KIMA)",
    sector: "كيماويات",
  },

  // ── PHARMACEUTICALS ───────────────────────────────────────────────────────
  {
    code: "PHAR",
    yahooCode: "EGS38381C017.CA",
    titleAr: "مصر للصناعات الدوائية",
    titleEn: "Egyptian International Pharmaceutical Industries (EIPICO)",
    sector: "أدوية",
  },
  {
    code: "ISPH",
    yahooCode: "EGS38341C011.CA",
    titleAr: "ابن سينا للأدوية",
    titleEn: "Ibnsina Pharma",
    sector: "أدوية",
  },
  {
    code: "NIPH",
    yahooCode: "EGS38331C012.CA",
    titleAr: "النيل للأدوية والصناعات الكيميائية",
    titleEn: "El-Nile Co. for Pharmaceuticals and Chemical Industries",
    sector: "أدوية",
  },
  {
    code: "OCPH",
    yahooCode: "EGS380R1C018.CA",
    titleAr: "أكتوبر للأدوية",
    titleEn: "October Pharma",
    sector: "أدوية",
  },
  {
    code: "AXPH",
    yahooCode: "EGS38321C013.CA",
    titleAr: "الإسكندرية للأدوية والصناعات الكيميائية",
    titleEn: "Alexandria Co. For Pharmaceuticals & Chemical Industries",
    sector: "أدوية",
  },
  {
    code: "MPCI",
    yahooCode: "EGS38351C010.CA",
    titleAr: "منفيس للأدوية والكيماويات",
    titleEn: "Memphis Pharmaceuticals & Chemical Industries",
    sector: "أدوية",
  },
  {
    code: "MCRO",
    yahooCode: "EGS7D971C011.CA",
    titleAr: "ماكرو جروب للصيدلانيات",
    titleEn: "Macro Group Pharmaceuticals",
    sector: "أدوية",
  },
  {
    code: "RMDA",
    yahooCode: "EGS381B1C015.CA",
    titleAr: "العاشر من رمضان للصناعات الدوائية",
    titleEn: "Tenth of Ramadan Pharmaceutical Industries (Rameda)",
    sector: "أدوية",
  },

  // ── FOOD & BEVERAGES ──────────────────────────────────────────────────────
  {
    code: "JUFO",
    yahooCode: "EGS74231C011.CA",
    titleAr: "جهينة للصناعات الغذائية",
    titleEn: "Juhayna Food Industries",
    sector: "غذاء",
  },
  {
    code: "EAST",
    yahooCode: "EGS37061C010.CA",
    titleAr: "الشركة الشرقية للدخان",
    titleEn: "Eastern Company (Tobacco)",
    sector: "غذاء",
  },
  {
    code: "OLFI",
    yahooCode: "EGS74181C010.CA",
    titleAr: "أراضي عبور للصناعات الغذائية",
    titleEn: "Obour Land for Food Industries",
    sector: "غذاء",
  },
  {
    code: "DOMT",
    yahooCode: "EGS74251C017.CA",
    titleAr: "الصناعات الغذائية العربية - دومتي",
    titleEn: "Arabian Food Industries (DOMTY)",
    sector: "غذاء",
  },

  // ── CEMENT ────────────────────────────────────────────────────────────────
  {
    code: "ARCC",
    yahooCode: "EGS3H031C013.CA",
    titleAr: "الأسمنت العربية",
    titleEn: "Arabian Cement Company",
    sector: "مواد بناء",
  },
  {
    code: "MCQE",
    yahooCode: "EGS3H021C014.CA",
    titleAr: "أسمنت مصر - قنا",
    titleEn: "Misr Cement (Qena)",
    sector: "مواد بناء",
  },
  {
    code: "MBSC",
    yahooCode: "EGS3H011C015.CA",
    titleAr: "أسمنت بني سويف",
    titleEn: "Misr Beni Suef Cement",
    sector: "مواد بناء",
  },
  {
    code: "SCEM",
    yahooCode: "EGS3H041C012.CA",
    titleAr: "أسمنت سيناء",
    titleEn: "Sinai Cement",
    sector: "مواد بناء",
  },
  {
    code: "SVCE",
    yahooCode: "EGS3H051C011.CA",
    titleAr: "أسمنت جنوب الوادي",
    titleEn: "South Valley Cement",
    sector: "مواد بناء",
  },
];
