export const WORLD_STOCKS_CONFIG = [
  // ══════════════════════════════════════════════════════════════════════════
  // 💻 تكنولوجيا أمريكية
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 1,
    ticker: "AAPL",
    slug: "apple",
    nameAr: "آبل",
    nameEn: "Apple Inc.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 2,
    ticker: "MSFT",
    slug: "microsoft",
    nameAr: "مايكروسوفت",
    nameEn: "Microsoft Corp.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 3,
    ticker: "NVDA",
    slug: "nvidia",
    nameAr: "إنفيديا",
    nameEn: "NVIDIA Corp.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 4,
    ticker: "GOOGL",
    slug: "google",
    nameAr: "ألفابيت جوجل",
    nameEn: "Alphabet Inc.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 5,
    ticker: "META",
    slug: "meta",
    nameAr: "ميتا",
    nameEn: "Meta Platforms",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 6,
    ticker: "AMZN",
    slug: "amazon",
    nameAr: "أمازون",
    nameEn: "Amazon.com Inc.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 7,
    ticker: "ORCL",
    slug: "oracle",
    nameAr: "أوراكل",
    nameEn: "Oracle Corp.",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 8,
    ticker: "CRM",
    slug: "salesforce",
    nameAr: "سيلزفورس",
    nameEn: "Salesforce Inc.",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 9,
    ticker: "INTC",
    slug: "intel",
    nameAr: "إنتل",
    nameEn: "Intel Corp.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 10,
    ticker: "AMD",
    slug: "amd",
    nameAr: "AMD",
    nameEn: "Advanced Micro Devices",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 11,
    ticker: "ADBE",
    slug: "adobe",
    nameAr: "أدوبي",
    nameEn: "Adobe Inc.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 12,
    ticker: "IBM",
    slug: "ibm",
    nameAr: "آي بي إم",
    nameEn: "IBM Corp.",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 13,
    ticker: "HPQ",
    slug: "hp",
    nameAr: "إتش بي",
    nameEn: "HP Inc.",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 14,
    ticker: "DELL",
    slug: "dell",
    nameAr: "ديل تكنولوجيز",
    nameEn: "Dell Technologies",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 15,
    ticker: "ACN",
    slug: "accenture",
    nameAr: "أكسنتشر",
    nameEn: "Accenture plc",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },

  // ── تكنولوجيا آسيوية وأوروبية ─────────────────────────────────────────────
  {
    id: 16,
    ticker: "ASML",
    slug: "asml",
    nameAr: "ASML هولندا",
    nameEn: "ASML Holding",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 17,
    ticker: "TSM",
    slug: "tsmc",
    nameAr: "TSMC تايوان",
    nameEn: "Taiwan Semiconductor",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 18,
    ticker: "SONY",
    slug: "sony",
    nameAr: "سوني",
    nameEn: "Sony Group Corp.",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 19,
    ticker: "SAP",
    slug: "sap",
    nameAr: "SAP الألمانية",
    nameEn: "SAP SE",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 20,
    ticker: "BABA",
    slug: "alibaba",
    nameAr: "علي بابا",
    nameEn: "Alibaba Group",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 21,
    ticker: "9988.HK",
    slug: "alibaba-hk",
    nameAr: "علي بابا هونغ كونغ",
    nameEn: "Alibaba HK",
    sector: "تكنولوجيا",
    exchange: "HKEX",
  },
  {
    id: 22,
    ticker: "005930.KS",
    slug: "samsung",
    nameAr: "سامسونج",
    nameEn: "Samsung Electronics",
    sector: "تكنولوجيا",
    exchange: "KRX",
  },
  {
    id: 23,
    ticker: "BIDU",
    slug: "baidu",
    nameAr: "بايدو الصينية",
    nameEn: "Baidu Inc.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 24,
    ticker: "TCEHY",
    slug: "tencent",
    nameAr: "تنسنت الصينية",
    nameEn: "Tencent Holdings",
    sector: "تكنولوجيا",
    exchange: "OTC",
  },
  {
    id: 25,
    ticker: "9618.HK",
    slug: "jd-hk",
    nameAr: "جي دي الصين",
    nameEn: "JD.com HK",
    sector: "تكنولوجيا",
    exchange: "HKEX",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🔬 أشباه موصلات
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 26,
    ticker: "QCOM",
    slug: "qualcomm",
    nameAr: "كوالكوم",
    nameEn: "Qualcomm Inc.",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 27,
    ticker: "TXN",
    slug: "texas-instruments",
    nameAr: "تكساس إنسترومنتس",
    nameEn: "Texas Instruments",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 28,
    ticker: "AMAT",
    slug: "applied-materials",
    nameAr: "أبلايد ماتيريالز",
    nameEn: "Applied Materials",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 29,
    ticker: "MU",
    slug: "micron",
    nameAr: "مايكرون",
    nameEn: "Micron Technology",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 30,
    ticker: "ARM",
    slug: "arm-holdings",
    nameAr: "آرم هولدينغز",
    nameEn: "Arm Holdings",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 31,
    ticker: "LRCX",
    slug: "lam-research",
    nameAr: "لام ريسيرش",
    nameEn: "Lam Research",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 32,
    ticker: "KLAC",
    slug: "kla-corp",
    nameAr: "KLA كورب",
    nameEn: "KLA Corp.",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 33,
    ticker: "NXPI",
    slug: "nxp-semi",
    nameAr: "NXP أشباه موصلات",
    nameEn: "NXP Semiconductors",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 34,
    ticker: "MCHP",
    slug: "microchip",
    nameAr: "مايكروشيب تكنولوجي",
    nameEn: "Microchip Technology",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 35,
    ticker: "ON",
    slug: "on-semi",
    nameAr: "أون سيميكندكتور",
    nameEn: "ON Semiconductor",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 36,
    ticker: "SWKS",
    slug: "skyworks",
    nameAr: "سكاي ووركس",
    nameEn: "Skyworks Solutions",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🤖 ذكاء اصطناعي
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 37,
    ticker: "PLTR",
    slug: "palantir",
    nameAr: "بالانتير",
    nameEn: "Palantir Technologies",
    sector: "ذكاء اصطناعي",
    exchange: "NASDAQ",
  },
  {
    id: 38,
    ticker: "CRWV",
    slug: "coreweave",
    nameAr: "كور ويف",
    nameEn: "CoreWeave Inc.",
    sector: "ذكاء اصطناعي",
    exchange: "NASDAQ",
  },
  {
    id: 39,
    ticker: "AI",
    slug: "c3ai",
    nameAr: "سي3 للذكاء الاصطناعي",
    nameEn: "C3.ai Inc.",
    sector: "ذكاء اصطناعي",
    exchange: "NYSE",
  },
  {
    id: 40,
    ticker: "PATH",
    slug: "uipath",
    nameAr: "يو آي باث",
    nameEn: "UiPath Inc.",
    sector: "ذكاء اصطناعي",
    exchange: "NYSE",
  },
  {
    id: 41,
    ticker: "SNOW",
    slug: "snowflake",
    nameAr: "سنوفليك",
    nameEn: "Snowflake Inc.",
    sector: "ذكاء اصطناعي",
    exchange: "NYSE",
  },
  {
    id: 42,
    ticker: "SMCI",
    slug: "supermicro",
    nameAr: "سوبر مايكرو",
    nameEn: "Super Micro Computer",
    sector: "ذكاء اصطناعي",
    exchange: "NASDAQ",
  },
  {
    id: 43,
    ticker: "AVGO",
    slug: "broadcom",
    nameAr: "برودكوم",
    nameEn: "Broadcom Inc.",
    sector: "ذكاء اصطناعي",
    exchange: "NASDAQ",
  },
  {
    id: 44,
    ticker: "MRVL",
    slug: "marvell",
    nameAr: "مارفيل تكنولوجي",
    nameEn: "Marvell Technology",
    sector: "ذكاء اصطناعي",
    exchange: "NASDAQ",
  },
  {
    id: 45,
    ticker: "NBIS",
    slug: "nebius",
    nameAr: "نيبيوس",
    nameEn: "Nebius Group",
    sector: "ذكاء اصطناعي",
    exchange: "NASDAQ",
  },
  {
    id: 46,
    ticker: "SOUN",
    slug: "soundhound",
    nameAr: "ساوند هاوند",
    nameEn: "SoundHound AI",
    sector: "ذكاء اصطناعي",
    exchange: "NASDAQ",
  },
  {
    id: 47,
    ticker: "BBAI",
    slug: "bigbear-ai",
    nameAr: "بيج بير للذكاء",
    nameEn: "BigBear.ai Holdings",
    sector: "ذكاء اصطناعي",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🔒 أمن سيبراني
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 48,
    ticker: "CRWD",
    slug: "crowdstrike",
    nameAr: "كراود سترايك",
    nameEn: "CrowdStrike Holdings",
    sector: "أمن سيبراني",
    exchange: "NASDAQ",
  },
  {
    id: 49,
    ticker: "PANW",
    slug: "paloalto",
    nameAr: "بالو ألتو نتووركس",
    nameEn: "Palo Alto Networks",
    sector: "أمن سيبراني",
    exchange: "NASDAQ",
  },
  {
    id: 50,
    ticker: "NET",
    slug: "cloudflare",
    nameAr: "كلاود فلير",
    nameEn: "Cloudflare Inc.",
    sector: "أمن سيبراني",
    exchange: "NYSE",
  },
  {
    id: 51,
    ticker: "ZS",
    slug: "zscaler",
    nameAr: "زي سكيلر",
    nameEn: "Zscaler Inc.",
    sector: "أمن سيبراني",
    exchange: "NASDAQ",
  },
  {
    id: 52,
    ticker: "S",
    slug: "sentinelone",
    nameAr: "سنتينل ون",
    nameEn: "SentinelOne Inc.",
    sector: "أمن سيبراني",
    exchange: "NYSE",
  },
  {
    id: 53,
    ticker: "FTNT",
    slug: "fortinet",
    nameAr: "فورتينيت",
    nameEn: "Fortinet Inc.",
    sector: "أمن سيبراني",
    exchange: "NASDAQ",
  },
  {
    id: 54,
    ticker: "OKTA",
    slug: "okta",
    nameAr: "أوكتا",
    nameEn: "Okta Inc.",
    sector: "أمن سيبراني",
    exchange: "NASDAQ",
  },
  {
    id: 55,
    ticker: "CYBR",
    slug: "cyberark",
    nameAr: "سايبر آرك",
    nameEn: "CyberArk Software",
    sector: "أمن سيبراني",
    exchange: "NASDAQ",
  },
  {
    id: 56,
    ticker: "CHKP",
    slug: "checkpoint",
    nameAr: "تشيك بوينت",
    nameEn: "Check Point Software",
    sector: "أمن سيبراني",
    exchange: "NASDAQ",
  },
  {
    id: 57,
    ticker: "QLYS",
    slug: "qualys",
    nameAr: "كواليس",
    nameEn: "Qualys Inc.",
    sector: "أمن سيبراني",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ☁️ سحابة وبرمجيات
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 58,
    ticker: "NOW",
    slug: "servicenow",
    nameAr: "سيرفيس ناو",
    nameEn: "ServiceNow Inc.",
    sector: "برمجيات",
    exchange: "NYSE",
  },
  {
    id: 59,
    ticker: "WDAY",
    slug: "workday",
    nameAr: "ووركداي",
    nameEn: "Workday Inc.",
    sector: "برمجيات",
    exchange: "NASDAQ",
  },
  {
    id: 60,
    ticker: "TEAM",
    slug: "atlassian",
    nameAr: "أتلاسيان",
    nameEn: "Atlassian Corp.",
    sector: "برمجيات",
    exchange: "NASDAQ",
  },
  {
    id: 61,
    ticker: "ZM",
    slug: "zoom",
    nameAr: "زووم",
    nameEn: "Zoom Video Comm.",
    sector: "برمجيات",
    exchange: "NASDAQ",
  },
  {
    id: 62,
    ticker: "DDOG",
    slug: "datadog",
    nameAr: "داتا دوج",
    nameEn: "Datadog Inc.",
    sector: "برمجيات",
    exchange: "NASDAQ",
  },
  {
    id: 63,
    ticker: "MDB",
    slug: "mongodb",
    nameAr: "مونغو دي بي",
    nameEn: "MongoDB Inc.",
    sector: "برمجيات",
    exchange: "NASDAQ",
  },
  {
    id: 64,
    ticker: "HUBS",
    slug: "hubspot",
    nameAr: "هاب سبوت",
    nameEn: "HubSpot Inc.",
    sector: "برمجيات",
    exchange: "NYSE",
  },
  {
    id: 65,
    ticker: "TWLO",
    slug: "twilio",
    nameAr: "تويليو",
    nameEn: "Twilio Inc.",
    sector: "برمجيات",
    exchange: "NYSE",
  },
  {
    id: 66,
    ticker: "GTLB",
    slug: "gitlab",
    nameAr: "جيت لاب",
    nameEn: "GitLab Inc.",
    sector: "برمجيات",
    exchange: "NASDAQ",
  },
  {
    id: 67,
    ticker: "VEEV",
    slug: "veeva",
    nameAr: "فيفا سيستمز",
    nameEn: "Veeva Systems",
    sector: "برمجيات",
    exchange: "NYSE",
  },
  {
    id: 68,
    ticker: "INTU",
    slug: "intuit",
    nameAr: "إنتويت",
    nameEn: "Intuit Inc.",
    sector: "برمجيات",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🏦 مالية وبنوك أمريكية
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 69,
    ticker: "JPM",
    slug: "jpmorgan",
    nameAr: "جي بي مورغان",
    nameEn: "JPMorgan Chase",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 70,
    ticker: "BAC",
    slug: "bofa",
    nameAr: "بنك أوف أمريكا",
    nameEn: "Bank of America",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 71,
    ticker: "GS",
    slug: "goldman",
    nameAr: "جولدمان ساكس",
    nameEn: "Goldman Sachs",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 72,
    ticker: "V",
    slug: "visa",
    nameAr: "فيزا",
    nameEn: "Visa Inc.",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 73,
    ticker: "MA",
    slug: "mastercard",
    nameAr: "ماستركارد",
    nameEn: "Mastercard Inc.",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 74,
    ticker: "MS",
    slug: "morgan-stanley",
    nameAr: "مورغان ستانلي",
    nameEn: "Morgan Stanley",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 75,
    ticker: "AXP",
    slug: "american-express",
    nameAr: "أمريكان إكسبريس",
    nameEn: "American Express",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 76,
    ticker: "C",
    slug: "citigroup",
    nameAr: "سيتي جروب",
    nameEn: "Citigroup Inc.",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 77,
    ticker: "BLK",
    slug: "blackrock",
    nameAr: "بلاك روك",
    nameEn: "BlackRock Inc.",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 78,
    ticker: "WFC",
    slug: "wells-fargo",
    nameAr: "ويلز فارجو",
    nameEn: "Wells Fargo",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 79,
    ticker: "USB",
    slug: "us-bancorp",
    nameAr: "يو إس بانكورب",
    nameEn: "U.S. Bancorp",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 80,
    ticker: "PNC",
    slug: "pnc-financial",
    nameAr: "PNC فايننشيال",
    nameEn: "PNC Financial Services",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 81,
    ticker: "SCHW",
    slug: "schwab",
    nameAr: "تشارلز شواب",
    nameEn: "Charles Schwab",
    sector: "مالية",
    exchange: "NYSE",
  },

  // ── بنوك دولية ────────────────────────────────────────────────────────────
  {
    id: 82,
    ticker: "HSBC",
    slug: "hsbc",
    nameAr: "إتش إس بي سي",
    nameEn: "HSBC Holdings",
    sector: "بنوك دولية",
    exchange: "NYSE",
  },
  {
    id: 83,
    ticker: "UBS",
    slug: "ubs",
    nameAr: "يو بي إس",
    nameEn: "UBS Group AG",
    sector: "بنوك دولية",
    exchange: "NYSE",
  },
  {
    id: 84,
    ticker: "DB",
    slug: "deutsche-bank",
    nameAr: "دويتشه بنك",
    nameEn: "Deutsche Bank",
    sector: "بنوك دولية",
    exchange: "NYSE",
  },
  {
    id: 85,
    ticker: "SAN",
    slug: "santander",
    nameAr: "سانتاندر",
    nameEn: "Banco Santander",
    sector: "بنوك دولية",
    exchange: "NYSE",
  },
  {
    id: 86,
    ticker: "ITUB",
    slug: "itau",
    nameAr: "إيتاو أونيبانكو",
    nameEn: "Itaú Unibanco",
    sector: "بنوك دولية",
    exchange: "NYSE",
  },
  {
    id: 87,
    ticker: "ING",
    slug: "ing-group",
    nameAr: "آي إن جي جروب",
    nameEn: "ING Group",
    sector: "بنوك دولية",
    exchange: "NYSE",
  },
  {
    id: 88,
    ticker: "MUFG",
    slug: "mufg",
    nameAr: "ميتسوبيشي UFJ المالية",
    nameEn: "Mitsubishi UFJ Financial",
    sector: "بنوك دولية",
    exchange: "NYSE",
  },
  {
    id: 89,
    ticker: "NMR",
    slug: "nomura",
    nameAr: "نومورا",
    nameEn: "Nomura Holdings",
    sector: "بنوك دولية",
    exchange: "NYSE",
  },

  // ── تأمين ─────────────────────────────────────────────────────────────────
  {
    id: 90,
    ticker: "BRK-B",
    slug: "berkshire",
    nameAr: "بيركشاير هاثاواي",
    nameEn: "Berkshire Hathaway B",
    sector: "تأمين",
    exchange: "NYSE",
  },
  {
    id: 91,
    ticker: "MET",
    slug: "metlife",
    nameAr: "ميتلايف",
    nameEn: "MetLife Inc.",
    sector: "تأمين",
    exchange: "NYSE",
  },
  {
    id: 92,
    ticker: "PRU",
    slug: "prudential",
    nameAr: "برودنشيال",
    nameEn: "Prudential Financial",
    sector: "تأمين",
    exchange: "NYSE",
  },
  {
    id: 93,
    ticker: "AFL",
    slug: "aflac",
    nameAr: "أفلاك",
    nameEn: "Aflac Inc.",
    sector: "تأمين",
    exchange: "NYSE",
  },
  {
    id: 94,
    ticker: "TRV",
    slug: "travelers",
    nameAr: "ترافيلرز",
    nameEn: "Travelers Companies",
    sector: "تأمين",
    exchange: "NYSE",
  },
  {
    id: 95,
    ticker: "CB",
    slug: "chubb",
    nameAr: "تشوب",
    nameEn: "Chubb Limited",
    sector: "تأمين",
    exchange: "NYSE",
  },
  {
    id: 96,
    ticker: "ALL",
    slug: "allstate",
    nameAr: "أولستيت",
    nameEn: "Allstate Corp.",
    sector: "تأمين",
    exchange: "NYSE",
  },
  {
    id: 97,
    ticker: "AIG",
    slug: "aig",
    nameAr: "AIG",
    nameEn: "American Intl. Group",
    sector: "تأمين",
    exchange: "NYSE",
  },
  {
    id: 98,
    ticker: "PGR",
    slug: "progressive",
    nameAr: "بروغريسيف",
    nameEn: "Progressive Corp.",
    sector: "تأمين",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ⛽ طاقة ونفط
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 99,
    ticker: "XOM",
    slug: "exxon",
    nameAr: "إكسون موبيل",
    nameEn: "Exxon Mobil Corp.",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 100,
    ticker: "CVX",
    slug: "chevron",
    nameAr: "شيفرون",
    nameEn: "Chevron Corp.",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 101,
    ticker: "2222.SR",
    slug: "aramco",
    nameAr: "أرامكو السعودية",
    nameEn: "Saudi Aramco",
    sector: "طاقة",
    exchange: "Tadawul",
  },
  {
    id: 102,
    ticker: "SHEL",
    slug: "shell",
    nameAr: "شيل",
    nameEn: "Shell plc",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 103,
    ticker: "TTE",
    slug: "totalenergies",
    nameAr: "توتال إنرجيز",
    nameEn: "TotalEnergies",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 104,
    ticker: "BP",
    slug: "bp",
    nameAr: "بي بي",
    nameEn: "BP plc",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 105,
    ticker: "COP",
    slug: "conocophillips",
    nameAr: "كونوكو فيليبس",
    nameEn: "ConocoPhillips",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 106,
    ticker: "SLB",
    slug: "schlumberger",
    nameAr: "شلمبرجير",
    nameEn: "Schlumberger",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 107,
    ticker: "EOG",
    slug: "eog-resources",
    nameAr: "إيوجي ريسورسز",
    nameEn: "EOG Resources",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 108,
    ticker: "PSX",
    slug: "phillips66",
    nameAr: "فيليبس 66",
    nameEn: "Phillips 66",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 109,
    ticker: "MPC",
    slug: "marathon-petro",
    nameAr: "ماراثون بتروليوم",
    nameEn: "Marathon Petroleum",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 110,
    ticker: "HAL",
    slug: "halliburton",
    nameAr: "هاليبرتون",
    nameEn: "Halliburton Co.",
    sector: "طاقة",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ⚡ طاقة متجددة
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 111,
    ticker: "ENPH",
    slug: "enphase",
    nameAr: "إنفيز إنيرجي",
    nameEn: "Enphase Energy",
    sector: "طاقة متجددة",
    exchange: "NASDAQ",
  },
  {
    id: 112,
    ticker: "FSLR",
    slug: "firstsolar",
    nameAr: "فيرست سولار",
    nameEn: "First Solar Inc.",
    sector: "طاقة متجددة",
    exchange: "NASDAQ",
  },
  {
    id: 113,
    ticker: "NEE",
    slug: "nextera",
    nameAr: "نيكست إيرا إنيرجي",
    nameEn: "NextEra Energy",
    sector: "طاقة متجددة",
    exchange: "NYSE",
  },
  {
    id: 114,
    ticker: "GEV",
    slug: "gevernova",
    nameAr: "GE فيرنوفا",
    nameEn: "GE Vernova Inc.",
    sector: "طاقة متجددة",
    exchange: "NYSE",
  },
  {
    id: 115,
    ticker: "SEDG",
    slug: "solaredge",
    nameAr: "سولار إيدج",
    nameEn: "SolarEdge Technologies",
    sector: "طاقة متجددة",
    exchange: "NASDAQ",
  },
  {
    id: 145,
    ticker: "SCATC.OL",
    slug: "Scatec",
    nameAr: "سكاتيك",
    nameEn: "Scatec ASA",
    sector: "طاقة متجددة",
    exchange: "NASDAQ",
  },
  {
    id: 116,
    ticker: "PLUG",
    slug: "plugpower",
    nameAr: "بلاج باور",
    nameEn: "Plug Power Inc.",
    sector: "طاقة متجددة",
    exchange: "NASDAQ",
  },
  {
    id: 117,
    ticker: "BE",
    slug: "bloom-energy",
    nameAr: "بلوم إنيرجي",
    nameEn: "Bloom Energy",
    sector: "طاقة متجددة",
    exchange: "NYSE",
  },
  {
    id: 118,
    ticker: "RUN",
    slug: "sunrun",
    nameAr: "صن رن",
    nameEn: "Sunrun Inc.",
    sector: "طاقة متجددة",
    exchange: "NASDAQ",
  },
  {
    id: 119,
    ticker: "ARRY",
    slug: "array-tech",
    nameAr: "آراي تكنولوجيز",
    nameEn: "Array Technologies",
    sector: "طاقة متجددة",
    exchange: "NASDAQ",
  },

  // ── مرافق عامة ────────────────────────────────────────────────────────────
  {
    id: 120,
    ticker: "DUK",
    slug: "duke-energy",
    nameAr: "ديوك إنيرجي",
    nameEn: "Duke Energy",
    sector: "مرافق عامة",
    exchange: "NYSE",
  },
  {
    id: 121,
    ticker: "SO",
    slug: "southern-company",
    nameAr: "الشركة الجنوبية",
    nameEn: "Southern Company",
    sector: "مرافق عامة",
    exchange: "NYSE",
  },
  {
    id: 122,
    ticker: "AEP",
    slug: "american-elec",
    nameAr: "أمريكان إليكتريك باور",
    nameEn: "American Electric Power",
    sector: "مرافق عامة",
    exchange: "NASDAQ",
  },
  {
    id: 123,
    ticker: "EXC",
    slug: "exelon",
    nameAr: "إكسيلون",
    nameEn: "Exelon Corp.",
    sector: "مرافق عامة",
    exchange: "NASDAQ",
  },
  {
    id: 124,
    ticker: "XEL",
    slug: "xcel-energy",
    nameAr: "إكسيل إنيرجي",
    nameEn: "Xcel Energy",
    sector: "مرافق عامة",
    exchange: "NASDAQ",
  },
  {
    id: 125,
    ticker: "D",
    slug: "dominion-energy",
    nameAr: "دومينيون إنيرجي",
    nameEn: "Dominion Energy",
    sector: "مرافق عامة",
    exchange: "NYSE",
  },
  {
    id: 126,
    ticker: "PCG",
    slug: "pg-and-e",
    nameAr: "PG&E كورب",
    nameEn: "PG&E Corp.",
    sector: "مرافق عامة",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 💊 رعاية صحية وصيدلة
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 127,
    ticker: "JNJ",
    slug: "jnj",
    nameAr: "جونسون آند جونسون",
    nameEn: "Johnson & Johnson",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 128,
    ticker: "UNH",
    slug: "unitedhealth",
    nameAr: "يونايتد هيلث",
    nameEn: "UnitedHealth Group",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 129,
    ticker: "PFE",
    slug: "pfizer",
    nameAr: "فايزر",
    nameEn: "Pfizer Inc.",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 130,
    ticker: "LLY",
    slug: "eli-lilly",
    nameAr: "إيلي ليلي",
    nameEn: "Eli Lilly and Co.",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 131,
    ticker: "NVO",
    slug: "novo-nordisk",
    nameAr: "نوفو نورديسك",
    nameEn: "Novo Nordisk",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 132,
    ticker: "ABBV",
    slug: "abbvie",
    nameAr: "آبفي",
    nameEn: "AbbVie Inc.",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 133,
    ticker: "MRK",
    slug: "merck",
    nameAr: "ميرك",
    nameEn: "Merck & Co.",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 134,
    ticker: "TMO",
    slug: "thermo-fisher",
    nameAr: "ثيرمو فيشر",
    nameEn: "Thermo Fisher",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 135,
    ticker: "BMY",
    slug: "bristol-myers",
    nameAr: "بريستول مايرز سكويب",
    nameEn: "Bristol Myers Squibb",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 136,
    ticker: "CVS",
    slug: "cvs-health",
    nameAr: "CVS هيلث",
    nameEn: "CVS Health Corp.",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 137,
    ticker: "MDT",
    slug: "medtronic",
    nameAr: "ميدترونيك",
    nameEn: "Medtronic plc",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 138,
    ticker: "SYK",
    slug: "stryker",
    nameAr: "سترايكر",
    nameEn: "Stryker Corp.",
    sector: "صحة",
    exchange: "NYSE",
  },

  // ── بيوتكنولوجيا ──────────────────────────────────────────────────────────
  {
    id: 139,
    ticker: "AMGN",
    slug: "amgen",
    nameAr: "أمجين",
    nameEn: "Amgen Inc.",
    sector: "بيوتكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 140,
    ticker: "GILD",
    slug: "gilead",
    nameAr: "جيليد ساينسز",
    nameEn: "Gilead Sciences",
    sector: "بيوتكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 141,
    ticker: "BIIB",
    slug: "biogen",
    nameAr: "بيوجين",
    nameEn: "Biogen Inc.",
    sector: "بيوتكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 142,
    ticker: "REGN",
    slug: "regeneron",
    nameAr: "ريجينيرون",
    nameEn: "Regeneron Pharma.",
    sector: "بيوتكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 143,
    ticker: "MRNA",
    slug: "moderna",
    nameAr: "موديرنا",
    nameEn: "Moderna Inc.",
    sector: "بيوتكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 144,
    ticker: "VRTX",
    slug: "vertex",
    nameAr: "فيرتكس فارما",
    nameEn: "Vertex Pharmaceuticals",
    sector: "بيوتكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 145,
    ticker: "ILMN",
    slug: "illumina",
    nameAr: "إيلومينا",
    nameEn: "Illumina Inc.",
    sector: "بيوتكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 146,
    ticker: "INCY",
    slug: "incyte",
    nameAr: "إنسايت",
    nameEn: "Incyte Corp.",
    sector: "بيوتكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 147,
    ticker: "EXAS",
    slug: "exact-sciences",
    nameAr: "إكساكت ساينسز",
    nameEn: "Exact Sciences",
    sector: "بيوتكنولوجيا",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🛒 استهلاك أساسي
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 148,
    ticker: "WMT",
    slug: "walmart",
    nameAr: "وول مارت",
    nameEn: "Walmart Inc.",
    sector: "استهلاك",
    exchange: "NYSE",
  },
  {
    id: 149,
    ticker: "KO",
    slug: "coca-cola",
    nameAr: "كوكا كولا",
    nameEn: "Coca-Cola Co.",
    sector: "استهلاك",
    exchange: "NYSE",
  },
  {
    id: 150,
    ticker: "PEP",
    slug: "pepsico",
    nameAr: "بيبسيكو",
    nameEn: "PepsiCo Inc.",
    sector: "استهلاك",
    exchange: "NASDAQ",
  },
  {
    id: 151,
    ticker: "PG",
    slug: "procter-gamble",
    nameAr: "بروكتر آند جامبل",
    nameEn: "Procter & Gamble",
    sector: "استهلاك",
    exchange: "NYSE",
  },
  {
    id: 152,
    ticker: "COST",
    slug: "costco",
    nameAr: "كوستكو",
    nameEn: "Costco Wholesale",
    sector: "استهلاك",
    exchange: "NASDAQ",
  },
  {
    id: 153,
    ticker: "TGT",
    slug: "target",
    nameAr: "تارجت",
    nameEn: "Target Corp.",
    sector: "استهلاك",
    exchange: "NYSE",
  },
  {
    id: 154,
    ticker: "NKE",
    slug: "nike",
    nameAr: "نايكي",
    nameEn: "NIKE Inc.",
    sector: "استهلاك",
    exchange: "NYSE",
  },
  {
    id: 155,
    ticker: "MDLZ",
    slug: "mondelez",
    nameAr: "موندليز",
    nameEn: "Mondelez Intl.",
    sector: "استهلاك",
    exchange: "NASDAQ",
  },
  {
    id: 156,
    ticker: "KHC",
    slug: "kraft-heinz",
    nameAr: "كرافت هاينز",
    nameEn: "Kraft Heinz Co.",
    sector: "استهلاك",
    exchange: "NASDAQ",
  },
  {
    id: 157,
    ticker: "GIS",
    slug: "general-mills",
    nameAr: "جنرال ميلز",
    nameEn: "General Mills Inc.",
    sector: "استهلاك",
    exchange: "NYSE",
  },
  {
    id: 158,
    ticker: "CL",
    slug: "colgate",
    nameAr: "كولجيت بالموليف",
    nameEn: "Colgate-Palmolive",
    sector: "استهلاك",
    exchange: "NYSE",
  },
  {
    id: 159,
    ticker: "PM",
    slug: "philip-morris",
    nameAr: "فيليب موريس",
    nameEn: "Philip Morris Intl.",
    sector: "استهلاك",
    exchange: "NYSE",
  },

  // ── مطاعم وترفيه غذائي ────────────────────────────────────────────────────
  {
    id: 160,
    ticker: "MCD",
    slug: "mcdonalds",
    nameAr: "ماكدونالدز",
    nameEn: "McDonald's Corp.",
    sector: "مطاعم",
    exchange: "NYSE",
  },
  {
    id: 161,
    ticker: "SBUX",
    slug: "starbucks",
    nameAr: "ستاربكس",
    nameEn: "Starbucks Corp.",
    sector: "مطاعم",
    exchange: "NASDAQ",
  },
  {
    id: 162,
    ticker: "YUM",
    slug: "yum-brands",
    nameAr: "يام براندز",
    nameEn: "Yum! Brands",
    sector: "مطاعم",
    exchange: "NYSE",
  },
  {
    id: 163,
    ticker: "CMG",
    slug: "chipotle",
    nameAr: "تشيبوتلي",
    nameEn: "Chipotle Mexican Grill",
    sector: "مطاعم",
    exchange: "NYSE",
  },
  {
    id: 164,
    ticker: "DPZ",
    slug: "dominos",
    nameAr: "دومينوز بيتزا",
    nameEn: "Domino's Pizza",
    sector: "مطاعم",
    exchange: "NASDAQ",
  },
  {
    id: 165,
    ticker: "QSR",
    slug: "restaurant-brands",
    nameAr: "ريستورانت براندز",
    nameEn: "Restaurant Brands Intl.",
    sector: "مطاعم",
    exchange: "NYSE",
  },
  {
    id: 166,
    ticker: "DRI",
    slug: "darden",
    nameAr: "داردن ريستورانتس",
    nameEn: "Darden Restaurants",
    sector: "مطاعم",
    exchange: "NYSE",
  },
  {
    id: 167,
    ticker: "WING",
    slug: "wingstop",
    nameAr: "وينج ستوب",
    nameEn: "Wingstop Inc.",
    sector: "مطاعم",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 👜 سلع فاخرة
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 168,
    ticker: "MC.PA",
    slug: "lvmh",
    nameAr: "LVMH للسلع الفاخرة",
    nameEn: "LVMH Moët Hennessy",
    sector: "سلع فاخرة",
    exchange: "EPA",
  },
  {
    id: 169,
    ticker: "RMS.PA",
    slug: "hermes",
    nameAr: "هيرميس",
    nameEn: "Hermès Intl.",
    sector: "سلع فاخرة",
    exchange: "EPA",
  },
  {
    id: 170,
    ticker: "CFR.SW",
    slug: "richemont",
    nameAr: "ريشمون",
    nameEn: "Compagnie Financière Richemont",
    sector: "سلع فاخرة",
    exchange: "SIX",
  },
  {
    id: 171,
    ticker: "KER.PA",
    slug: "kering",
    nameAr: "كيرينج",
    nameEn: "Kering SA",
    sector: "سلع فاخرة",
    exchange: "EPA",
  },
  {
    id: 172,
    ticker: "RL",
    slug: "ralph-lauren",
    nameAr: "رالف لورين",
    nameEn: "Ralph Lauren Corp.",
    sector: "سلع فاخرة",
    exchange: "NYSE",
  },
  {
    id: 173,
    ticker: "CPRI",
    slug: "capri-holdings",
    nameAr: "كابري هولدينغز",
    nameEn: "Capri Holdings",
    sector: "سلع فاخرة",
    exchange: "NYSE",
  },
  {
    id: 174,
    ticker: "TPR",
    slug: "tapestry",
    nameAr: "تابستري (كوتش)",
    nameEn: "Tapestry Inc.",
    sector: "سلع فاخرة",
    exchange: "NYSE",
  },
  {
    id: 175,
    ticker: "EL",
    slug: "estee-lauder",
    nameAr: "إيستي لودر",
    nameEn: "Estée Lauder Companies",
    sector: "سلع فاخرة",
    exchange: "NYSE",
  },
  {
    id: 176,
    ticker: "BRBY.L",
    slug: "burberry",
    nameAr: "بيربيري",
    nameEn: "Burberry Group plc",
    sector: "سلع فاخرة",
    exchange: "LSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🚗 سيارات
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 177,
    ticker: "TSLA",
    slug: "tesla",
    nameAr: "تسلا",
    nameEn: "Tesla Inc.",
    sector: "سيارات",
    exchange: "NASDAQ",
  },
  {
    id: 178,
    ticker: "TM",
    slug: "toyota",
    nameAr: "تويوتا",
    nameEn: "Toyota Motor",
    sector: "سيارات",
    exchange: "NYSE",
  },
  {
    id: 179,
    ticker: "F",
    slug: "ford",
    nameAr: "فورد",
    nameEn: "Ford Motor Co.",
    sector: "سيارات",
    exchange: "NYSE",
  },
  {
    id: 180,
    ticker: "GM",
    slug: "general-motors",
    nameAr: "جنرال موتورز",
    nameEn: "General Motors",
    sector: "سيارات",
    exchange: "NYSE",
  },
  {
    id: 181,
    ticker: "RACE",
    slug: "ferrari",
    nameAr: "فيراري",
    nameEn: "Ferrari N.V.",
    sector: "سيارات",
    exchange: "NYSE",
  },
  {
    id: 182,
    ticker: "STLA",
    slug: "stellantis",
    nameAr: "ستيلانتس",
    nameEn: "Stellantis N.V.",
    sector: "سيارات",
    exchange: "NYSE",
  },
  {
    id: 183,
    ticker: "HMC",
    slug: "honda",
    nameAr: "هوندا موتور",
    nameEn: "Honda Motor Co.",
    sector: "سيارات",
    exchange: "NYSE",
  },
  {
    id: 184,
    ticker: "VWAGY",
    slug: "volkswagen",
    nameAr: "فولكسواغن",
    nameEn: "Volkswagen AG",
    sector: "سيارات",
    exchange: "OTC",
  },
  {
    id: 185,
    ticker: "BMWYY",
    slug: "bmw",
    nameAr: "BMW",
    nameEn: "BMW AG",
    sector: "سيارات",
    exchange: "OTC",
  },
  {
    id: 186,
    ticker: "MBGYY",
    slug: "mercedes",
    nameAr: "مرسيدس بنز",
    nameEn: "Mercedes-Benz Group",
    sector: "سيارات",
    exchange: "OTC",
  },

  // ── سيارات كهربائية ────────────────────────────────────────────────────────
  {
    id: 187,
    ticker: "RIVN",
    slug: "rivian",
    nameAr: "ريفيان",
    nameEn: "Rivian Automotive",
    sector: "سيارات كهربائية",
    exchange: "NASDAQ",
  },
  {
    id: 188,
    ticker: "NIO",
    slug: "nio",
    nameAr: "نيو الصينية",
    nameEn: "NIO Inc.",
    sector: "سيارات كهربائية",
    exchange: "NYSE",
  },
  {
    id: 189,
    ticker: "LCID",
    slug: "lucid",
    nameAr: "لوسيد موتورز",
    nameEn: "Lucid Group Inc.",
    sector: "سيارات كهربائية",
    exchange: "NASDAQ",
  },
  {
    id: 190,
    ticker: "LI",
    slug: "li-auto",
    nameAr: "لي أوتو الصينية",
    nameEn: "Li Auto Inc.",
    sector: "سيارات كهربائية",
    exchange: "NASDAQ",
  },
  {
    id: 191,
    ticker: "XPEV",
    slug: "xpeng",
    nameAr: "إكس بينج الصينية",
    nameEn: "XPeng Inc.",
    sector: "سيارات كهربائية",
    exchange: "NYSE",
  },
  {
    id: 192,
    ticker: "BYDDY",
    slug: "byd",
    nameAr: "BYD الصينية",
    nameEn: "BYD Company",
    sector: "سيارات كهربائية",
    exchange: "OTC",
  },
  {
    id: 193,
    ticker: "FSR",
    slug: "fisker",
    nameAr: "فيسكر",
    nameEn: "Fisker Inc.",
    sector: "سيارات كهربائية",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ✈️ دفاع وفضاء
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 194,
    ticker: "LMT",
    slug: "lockheed",
    nameAr: "لوكهيد مارتن",
    nameEn: "Lockheed Martin",
    sector: "دفاع وفضاء",
    exchange: "NYSE",
  },
  {
    id: 195,
    ticker: "RTX",
    slug: "rtx",
    nameAr: "RTX كورب",
    nameEn: "RTX Corp.",
    sector: "دفاع وفضاء",
    exchange: "NYSE",
  },
  {
    id: 196,
    ticker: "BA",
    slug: "boeing",
    nameAr: "بوينج",
    nameEn: "Boeing Co.",
    sector: "دفاع وفضاء",
    exchange: "NYSE",
  },
  {
    id: 197,
    ticker: "RKLB",
    slug: "rocketlab",
    nameAr: "روكيت لاب",
    nameEn: "Rocket Lab USA",
    sector: "دفاع وفضاء",
    exchange: "NASDAQ",
  },
  {
    id: 198,
    ticker: "JOBY",
    slug: "joby",
    nameAr: "جوبي أفيشن",
    nameEn: "Joby Aviation",
    sector: "دفاع وفضاء",
    exchange: "NYSE",
  },
  {
    id: 199,
    ticker: "NOC",
    slug: "northrop",
    nameAr: "نورثروب جرومان",
    nameEn: "Northrop Grumman",
    sector: "دفاع وفضاء",
    exchange: "NYSE",
  },
  {
    id: 200,
    ticker: "GD",
    slug: "general-dynamics",
    nameAr: "جنرال ديناميكس",
    nameEn: "General Dynamics",
    sector: "دفاع وفضاء",
    exchange: "NYSE",
  },
  {
    id: 201,
    ticker: "HII",
    slug: "huntington",
    nameAr: "هانتينغتون إنغالز",
    nameEn: "Huntington Ingalls",
    sector: "دفاع وفضاء",
    exchange: "NYSE",
  },
  {
    id: 202,
    ticker: "ACHR",
    slug: "archer-aviation",
    nameAr: "آرشر أفيشن",
    nameEn: "Archer Aviation",
    sector: "دفاع وفضاء",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 💳 فينتك وعملات رقمية
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 203,
    ticker: "COIN",
    slug: "coinbase",
    nameAr: "كوينبيس",
    nameEn: "Coinbase Global",
    sector: "فينتك وكريبتو",
    exchange: "NASDAQ",
  },
  {
    id: 204,
    ticker: "MSTR",
    slug: "microstrategy",
    nameAr: "مايكرو ستراتيجي",
    nameEn: "MicroStrategy Inc.",
    sector: "فينتك وكريبتو",
    exchange: "NASDAQ",
  },
  {
    id: 205,
    ticker: "PYPL",
    slug: "paypal",
    nameAr: "باي بال",
    nameEn: "PayPal Holdings",
    sector: "فينتك وكريبتو",
    exchange: "NASDAQ",
  },
  {
    id: 206,
    ticker: "SQ",
    slug: "block",
    nameAr: "بلوك (سكوير)",
    nameEn: "Block Inc.",
    sector: "فينتك وكريبتو",
    exchange: "NYSE",
  },
  {
    id: 207,
    ticker: "SOFI",
    slug: "sofi",
    nameAr: "سوفاي تكنولوجيز",
    nameEn: "SoFi Technologies",
    sector: "فينتك وكريبتو",
    exchange: "NASDAQ",
  },
  {
    id: 208,
    ticker: "HOOD",
    slug: "robinhood",
    nameAr: "روبين هود",
    nameEn: "Robinhood Markets",
    sector: "فينتك وكريبتو",
    exchange: "NASDAQ",
  },
  {
    id: 209,
    ticker: "AFRM",
    slug: "affirm",
    nameAr: "أفيرم",
    nameEn: "Affirm Holdings",
    sector: "فينتك وكريبتو",
    exchange: "NASDAQ",
  },
  {
    id: 210,
    ticker: "UPST",
    slug: "upstart",
    nameAr: "أبستارت",
    nameEn: "Upstart Holdings",
    sector: "فينتك وكريبتو",
    exchange: "NASDAQ",
  },
  {
    id: 211,
    ticker: "NU",
    slug: "nubank",
    nameAr: "نيو بنك",
    nameEn: "Nu Holdings",
    sector: "فينتك وكريبتو",
    exchange: "NYSE",
  },
  {
    id: 212,
    ticker: "IBIT",
    slug: "ishares-bitcoin",
    nameAr: "آي شيرز بيتكوين",
    nameEn: "iShares Bitcoin Trust",
    sector: "فينتك وكريبتو",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🛒 تجارة إلكترونية
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 213,
    ticker: "SHOP",
    slug: "shopify",
    nameAr: "شوبيفاي",
    nameEn: "Shopify Inc.",
    sector: "تجارة إلكترونية",
    exchange: "NYSE",
  },
  {
    id: 214,
    ticker: "MELI",
    slug: "mercadolibre",
    nameAr: "ميركادو ليبري",
    nameEn: "MercadoLibre Inc.",
    sector: "تجارة إلكترونية",
    exchange: "NASDAQ",
  },
  {
    id: 215,
    ticker: "SE",
    slug: "sea-limited",
    nameAr: "سي ليميتد",
    nameEn: "Sea Limited",
    sector: "تجارة إلكترونية",
    exchange: "NYSE",
  },
  {
    id: 216,
    ticker: "PDD",
    slug: "pinduoduo",
    nameAr: "بيندودو / تيمو",
    nameEn: "PDD Holdings",
    sector: "تجارة إلكترونية",
    exchange: "NASDAQ",
  },
  {
    id: 217,
    ticker: "EBAY",
    slug: "ebay",
    nameAr: "إيباي",
    nameEn: "eBay Inc.",
    sector: "تجارة إلكترونية",
    exchange: "NASDAQ",
  },
  {
    id: 218,
    ticker: "CPNG",
    slug: "coupang",
    nameAr: "كوبانغ",
    nameEn: "Coupang Inc.",
    sector: "تجارة إلكترونية",
    exchange: "NYSE",
  },
  {
    id: 219,
    ticker: "W",
    slug: "wayfair",
    nameAr: "ويفير",
    nameEn: "Wayfair Inc.",
    sector: "تجارة إلكترونية",
    exchange: "NYSE",
  },
  {
    id: 220,
    ticker: "ETSY",
    slug: "etsy",
    nameAr: "إتسي",
    nameEn: "Etsy Inc.",
    sector: "تجارة إلكترونية",
    exchange: "NASDAQ",
  },
  {
    id: 221,
    ticker: "JD",
    slug: "jd-com",
    nameAr: "جي دي دوت كوم",
    nameEn: "JD.com Inc.",
    sector: "تجارة إلكترونية",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 📱 وسائل التواصل والترفيه
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 222,
    ticker: "SNAP",
    slug: "snapchat",
    nameAr: "سناب شات",
    nameEn: "Snap Inc.",
    sector: "وسائل التواصل",
    exchange: "NYSE",
  },
  {
    id: 223,
    ticker: "PINS",
    slug: "pinterest",
    nameAr: "بينتريست",
    nameEn: "Pinterest Inc.",
    sector: "وسائل التواصل",
    exchange: "NYSE",
  },
  {
    id: 224,
    ticker: "RDDT",
    slug: "reddit",
    nameAr: "ريديت",
    nameEn: "Reddit Inc.",
    sector: "وسائل التواصل",
    exchange: "NYSE",
  },
  {
    id: 225,
    ticker: "SPOT",
    slug: "spotify",
    nameAr: "سبوتيفاي",
    nameEn: "Spotify Technology",
    sector: "وسائل التواصل",
    exchange: "NYSE",
  },
  {
    id: 226,
    ticker: "MTCH",
    slug: "match-group",
    nameAr: "ماتش جروب (تيندر)",
    nameEn: "Match Group Inc.",
    sector: "وسائل التواصل",
    exchange: "NASDAQ",
  },
  {
    id: 227,
    ticker: "BMBL",
    slug: "bumble",
    nameAr: "بامبل",
    nameEn: "Bumble Inc.",
    sector: "وسائل التواصل",
    exchange: "NASDAQ",
  },
  {
    id: 228,
    ticker: "TTD",
    slug: "trade-desk",
    nameAr: "ذا تريد ديسك",
    nameEn: "The Trade Desk",
    sector: "وسائل التواصل",
    exchange: "NASDAQ",
  },

  // ── إعلام وترفيه ──────────────────────────────────────────────────────────
  {
    id: 229,
    ticker: "NFLX",
    slug: "netflix",
    nameAr: "نتفليكس",
    nameEn: "Netflix Inc.",
    sector: "إعلام وترفيه",
    exchange: "NASDAQ",
  },
  {
    id: 230,
    ticker: "DIS",
    slug: "disney",
    nameAr: "ديزني",
    nameEn: "Walt Disney Co.",
    sector: "إعلام وترفيه",
    exchange: "NYSE",
  },
  {
    id: 231,
    ticker: "WBD",
    slug: "warner-bros",
    nameAr: "وارنر براذرز",
    nameEn: "Warner Bros. Discovery",
    sector: "إعلام وترفيه",
    exchange: "NASDAQ",
  },
  {
    id: 232,
    ticker: "PARA",
    slug: "paramount",
    nameAr: "باراماونت جلوبال",
    nameEn: "Paramount Global",
    sector: "إعلام وترفيه",
    exchange: "NASDAQ",
  },
  {
    id: 233,
    ticker: "LYV",
    slug: "live-nation",
    nameAr: "لايف نيشن",
    nameEn: "Live Nation Entertainment",
    sector: "إعلام وترفيه",
    exchange: "NYSE",
  },
  {
    id: 234,
    ticker: "IMAX",
    slug: "imax",
    nameAr: "آيماكس",
    nameEn: "IMAX Corp.",
    sector: "إعلام وترفيه",
    exchange: "NYSE",
  },

  // ── ألعاب ─────────────────────────────────────────────────────────────────
  {
    id: 235,
    ticker: "RBLX",
    slug: "roblox",
    nameAr: "روبلوكس",
    nameEn: "Roblox Corp.",
    sector: "ألعاب",
    exchange: "NYSE",
  },
  {
    id: 236,
    ticker: "EA",
    slug: "ea-games",
    nameAr: "إليكترونيك آرتس",
    nameEn: "Electronic Arts",
    sector: "ألعاب",
    exchange: "NASDAQ",
  },
  {
    id: 237,
    ticker: "TTWO",
    slug: "take-two",
    nameAr: "تيك تو إنتراكتيف",
    nameEn: "Take-Two Interactive",
    sector: "ألعاب",
    exchange: "NASDAQ",
  },
  {
    id: 238,
    ticker: "NTDOY",
    slug: "nintendo",
    nameAr: "نينتندو",
    nameEn: "Nintendo Co.",
    sector: "ألعاب",
    exchange: "OTC",
  },
  {
    id: 239,
    ticker: "DKNG",
    slug: "draftkings",
    nameAr: "درافت كينجز",
    nameEn: "DraftKings Inc.",
    sector: "ألعاب",
    exchange: "NASDAQ",
  },
  {
    id: 240,
    ticker: "NEXOF",
    slug: "nexon",
    nameAr: "نيكسون كوريا",
    nameEn: "Nexon Co.",
    sector: "ألعاب",
    exchange: "OTC",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🚕 تنقل وسفر
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 241,
    ticker: "UBER",
    slug: "uber",
    nameAr: "أوبر",
    nameEn: "Uber Technologies",
    sector: "تنقل وسفر",
    exchange: "NYSE",
  },
  {
    id: 242,
    ticker: "LYFT",
    slug: "lyft",
    nameAr: "ليفت",
    nameEn: "Lyft Inc.",
    sector: "تنقل وسفر",
    exchange: "NASDAQ",
  },
  {
    id: 243,
    ticker: "ABNB",
    slug: "airbnb",
    nameAr: "إير بي إن بي",
    nameEn: "Airbnb Inc.",
    sector: "تنقل وسفر",
    exchange: "NASDAQ",
  },
  {
    id: 244,
    ticker: "BKNG",
    slug: "booking",
    nameAr: "بوكينج هولدينغز",
    nameEn: "Booking Holdings",
    sector: "تنقل وسفر",
    exchange: "NASDAQ",
  },
  {
    id: 245,
    ticker: "DAL",
    slug: "delta",
    nameAr: "خطوط دلتا",
    nameEn: "Delta Air Lines",
    sector: "تنقل وسفر",
    exchange: "NYSE",
  },
  {
    id: 246,
    ticker: "AAL",
    slug: "american-airlines",
    nameAr: "الخطوط الأمريكية",
    nameEn: "American Airlines",
    sector: "تنقل وسفر",
    exchange: "NASDAQ",
  },
  {
    id: 247,
    ticker: "UAL",
    slug: "united-airlines",
    nameAr: "يونايتد إيرلاينز",
    nameEn: "United Airlines",
    sector: "تنقل وسفر",
    exchange: "NASDAQ",
  },
  {
    id: 248,
    ticker: "LUV",
    slug: "southwest",
    nameAr: "ساوث ويست إيرلاينز",
    nameEn: "Southwest Airlines",
    sector: "تنقل وسفر",
    exchange: "NYSE",
  },
  {
    id: 249,
    ticker: "MAR",
    slug: "marriott",
    nameAr: "ماريوت إنترناشيونال",
    nameEn: "Marriott International",
    sector: "تنقل وسفر",
    exchange: "NASDAQ",
  },
  {
    id: 250,
    ticker: "HLT",
    slug: "hilton",
    nameAr: "هيلتون ووردلوايد",
    nameEn: "Hilton Worldwide",
    sector: "تنقل وسفر",
    exchange: "NYSE",
  },
  {
    id: 251,
    ticker: "H",
    slug: "hyatt",
    nameAr: "هيات هوتيلز",
    nameEn: "Hyatt Hotels Corp.",
    sector: "تنقل وسفر",
    exchange: "NYSE",
  },
  {
    id: 252,
    ticker: "RCL",
    slug: "royal-caribbean",
    nameAr: "رويال كاريبيان",
    nameEn: "Royal Caribbean Group",
    sector: "تنقل وسفر",
    exchange: "NYSE",
  },
  {
    id: 253,
    ticker: "CCL",
    slug: "carnival",
    nameAr: "كارنيفال كروز",
    nameEn: "Carnival Corporation",
    sector: "تنقل وسفر",
    exchange: "NYSE",
  },

  // ── نقل ولوجستيات ─────────────────────────────────────────────────────────
  {
    id: 254,
    ticker: "UPS",
    slug: "ups",
    nameAr: "يو بي إس",
    nameEn: "United Parcel Service",
    sector: "نقل ولوجستيات",
    exchange: "NYSE",
  },
  {
    id: 255,
    ticker: "FDX",
    slug: "fedex",
    nameAr: "فيديكس",
    nameEn: "FedEx Corp.",
    sector: "نقل ولوجستيات",
    exchange: "NYSE",
  },
  {
    id: 256,
    ticker: "UNP",
    slug: "union-pacific",
    nameAr: "يونيون باسيفيك",
    nameEn: "Union Pacific",
    sector: "نقل ولوجستيات",
    exchange: "NYSE",
  },
  {
    id: 257,
    ticker: "CSX",
    slug: "csx",
    nameAr: "CSX كورب",
    nameEn: "CSX Corp.",
    sector: "نقل ولوجستيات",
    exchange: "NASDAQ",
  },
  {
    id: 258,
    ticker: "NSC",
    slug: "norfolk-southern",
    nameAr: "نورفولك ساذرن",
    nameEn: "Norfolk Southern",
    sector: "نقل ولوجستيات",
    exchange: "NYSE",
  },
  {
    id: 259,
    ticker: "XPO",
    slug: "xpo-logistics",
    nameAr: "XPO لوجستكس",
    nameEn: "XPO Inc.",
    sector: "نقل ولوجستيات",
    exchange: "NYSE",
  },
  {
    id: 260,
    ticker: "EXPD",
    slug: "expeditors",
    nameAr: "إكسبيديتورز",
    nameEn: "Expeditors Intl.",
    sector: "نقل ولوجستيات",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 📡 اتصالات
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 261,
    ticker: "T",
    slug: "att",
    nameAr: "AT&T",
    nameEn: "AT&T Inc.",
    sector: "اتصالات",
    exchange: "NYSE",
  },
  {
    id: 262,
    ticker: "VZ",
    slug: "verizon",
    nameAr: "فيريزون",
    nameEn: "Verizon Comm.",
    sector: "اتصالات",
    exchange: "NYSE",
  },
  {
    id: 263,
    ticker: "TMUS",
    slug: "tmobile",
    nameAr: "تي-موبايل",
    nameEn: "T-Mobile US",
    sector: "اتصالات",
    exchange: "NASDAQ",
  },
  {
    id: 264,
    ticker: "VOD",
    slug: "vodafone",
    nameAr: "فودافون",
    nameEn: "Vodafone Group",
    sector: "اتصالات",
    exchange: "NASDAQ",
  },
  {
    id: 265,
    ticker: "CMCSA",
    slug: "comcast",
    nameAr: "كومكاست",
    nameEn: "Comcast Corp.",
    sector: "اتصالات",
    exchange: "NASDAQ",
  },
  {
    id: 266,
    ticker: "CHTR",
    slug: "charter-comm",
    nameAr: "تشارتر كوميونيكيشنز",
    nameEn: "Charter Communications",
    sector: "اتصالات",
    exchange: "NASDAQ",
  },
  {
    id: 267,
    ticker: "ORAN",
    slug: "orange-sa",
    nameAr: "أورانج الفرنسية",
    nameEn: "Orange S.A.",
    sector: "اتصالات",
    exchange: "NYSE",
  },
  {
    id: 268,
    ticker: "TEF",
    slug: "telefonica",
    nameAr: "تيليفونيكا",
    nameEn: "Telefónica S.A.",
    sector: "اتصالات",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🏭 صناعة وتشييد
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 269,
    ticker: "CAT",
    slug: "caterpillar",
    nameAr: "كاتربيلر",
    nameEn: "Caterpillar Inc.",
    sector: "صناعة",
    exchange: "NYSE",
  },
  {
    id: 270,
    ticker: "DE",
    slug: "deere",
    nameAr: "جون ديري",
    nameEn: "Deere & Company",
    sector: "صناعة",
    exchange: "NYSE",
  },
  {
    id: 271,
    ticker: "HON",
    slug: "honeywell",
    nameAr: "هانيويل",
    nameEn: "Honeywell Intl.",
    sector: "صناعة",
    exchange: "NASDAQ",
  },
  {
    id: 272,
    ticker: "GE",
    slug: "ge-aerospace",
    nameAr: "GE للطيران",
    nameEn: "GE Aerospace",
    sector: "صناعة",
    exchange: "NYSE",
  },
  {
    id: 273,
    ticker: "MMM",
    slug: "3m",
    nameAr: "ثري إم",
    nameEn: "3M Company",
    sector: "صناعة",
    exchange: "NYSE",
  },
  {
    id: 274,
    ticker: "ETN",
    slug: "eaton",
    nameAr: "إيتون كورب",
    nameEn: "Eaton Corp.",
    sector: "صناعة",
    exchange: "NYSE",
  },
  {
    id: 275,
    ticker: "EMR",
    slug: "emerson",
    nameAr: "إيمرسون إليكتريك",
    nameEn: "Emerson Electric",
    sector: "صناعة",
    exchange: "NYSE",
  },
  {
    id: 276,
    ticker: "ITW",
    slug: "illinois-tool",
    nameAr: "إيلينوي تول ووركس",
    nameEn: "Illinois Tool Works",
    sector: "صناعة",
    exchange: "NYSE",
  },
  {
    id: 277,
    ticker: "PH",
    slug: "parker-hannifin",
    nameAr: "باركر هانيفين",
    nameEn: "Parker-Hannifin",
    sector: "صناعة",
    exchange: "NYSE",
  },
  {
    id: 278,
    ticker: "ROK",
    slug: "rockwell",
    nameAr: "روكويل أوتوميشن",
    nameEn: "Rockwell Automation",
    sector: "صناعة",
    exchange: "NYSE",
  },
  {
    id: 279,
    ticker: "IR",
    slug: "ingersoll-rand",
    nameAr: "إنجرسول راند",
    nameEn: "Ingersoll Rand Inc.",
    sector: "صناعة",
    exchange: "NYSE",
  },
  {
    id: 280,
    ticker: "SIEGY",
    slug: "siemens",
    nameAr: "سيمنز",
    nameEn: "Siemens AG",
    sector: "صناعة",
    exchange: "OTC",
  },
  {
    id: 281,
    ticker: "ABB",
    slug: "abb-ltd",
    nameAr: "ABB المجموعة",
    nameEn: "ABB Ltd.",
    sector: "صناعة",
    exchange: "NYSE",
  },

  // ── مواد أساسية ────────────────────────────────────────────────────────────
  {
    id: 282,
    ticker: "LIN",
    slug: "linde",
    nameAr: "ليندي",
    nameEn: "Linde plc",
    sector: "مواد أساسية",
    exchange: "NASDAQ",
  },
  {
    id: 283,
    ticker: "DOW",
    slug: "dow-inc",
    nameAr: "داو الكيميائية",
    nameEn: "Dow Inc.",
    sector: "مواد أساسية",
    exchange: "NYSE",
  },
  {
    id: 284,
    ticker: "DD",
    slug: "dupont",
    nameAr: "ديوبونت",
    nameEn: "DuPont de Nemours",
    sector: "مواد أساسية",
    exchange: "NYSE",
  },
  {
    id: 285,
    ticker: "LYB",
    slug: "lyondell",
    nameAr: "لايونديل باسيل",
    nameEn: "LyondellBasell",
    sector: "مواد أساسية",
    exchange: "NYSE",
  },
  {
    id: 286,
    ticker: "PPG",
    slug: "ppg-industries",
    nameAr: "PPG إندستريز",
    nameEn: "PPG Industries",
    sector: "مواد أساسية",
    exchange: "NYSE",
  },
  {
    id: 287,
    ticker: "ECL",
    slug: "ecolab",
    nameAr: "إيكولاب",
    nameEn: "Ecolab Inc.",
    sector: "مواد أساسية",
    exchange: "NYSE",
  },
  {
    id: 288,
    ticker: "APD",
    slug: "air-products",
    nameAr: "إير برودكتس",
    nameEn: "Air Products & Chemicals",
    sector: "مواد أساسية",
    exchange: "NASDAQ",
  },
  {
    id: 289,
    ticker: "SHW",
    slug: "sherwin-williams",
    nameAr: "شيروين ويليامز",
    nameEn: "Sherwin-Williams",
    sector: "مواد أساسية",
    exchange: "NYSE",
  },

  // ── تعدين ومواد ────────────────────────────────────────────────────────────
  {
    id: 290,
    ticker: "BHP",
    slug: "bhp",
    nameAr: "بي إتش بي",
    nameEn: "BHP Group",
    sector: "تعدين ومواد",
    exchange: "NYSE",
  },
  {
    id: 291,
    ticker: "RIO",
    slug: "rio-tinto",
    nameAr: "ريو تينتو",
    nameEn: "Rio Tinto",
    sector: "تعدين ومواد",
    exchange: "NYSE",
  },
  {
    id: 292,
    ticker: "FCX",
    slug: "freeport",
    nameAr: "فريبورت مكموران",
    nameEn: "Freeport-McMoRan",
    sector: "تعدين ومواد",
    exchange: "NYSE",
  },
  {
    id: 293,
    ticker: "NEM",
    slug: "newmont",
    nameAr: "نيومونت",
    nameEn: "Newmont Corp.",
    sector: "تعدين ومواد",
    exchange: "NYSE",
  },
  {
    id: 294,
    ticker: "GOLD",
    slug: "barrick-gold",
    nameAr: "باريك الذهب",
    nameEn: "Barrick Gold Corp.",
    sector: "تعدين ومواد",
    exchange: "NYSE",
  },
  {
    id: 295,
    ticker: "AA",
    slug: "alcoa",
    nameAr: "ألكوا",
    nameEn: "Alcoa Corp.",
    sector: "تعدين ومواد",
    exchange: "NYSE",
  },
  {
    id: 296,
    ticker: "VALE",
    slug: "vale",
    nameAr: "فالي البرازيل",
    nameEn: "Vale S.A.",
    sector: "تعدين ومواد",
    exchange: "NYSE",
  },
  {
    id: 297,
    ticker: "SCCO",
    slug: "southern-copper",
    nameAr: "ساذرن كوبر",
    nameEn: "Southern Copper Corp.",
    sector: "تعدين ومواد",
    exchange: "NYSE",
  },
  {
    id: 298,
    ticker: "CLF",
    slug: "cleveland-cliffs",
    nameAr: "كليفلاند كليفس",
    nameEn: "Cleveland-Cliffs",
    sector: "تعدين ومواد",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🏢 عقارات (REITs)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 299,
    ticker: "PLD",
    slug: "prologis",
    nameAr: "برولوجيس",
    nameEn: "Prologis Inc.",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 300,
    ticker: "AMT",
    slug: "american-tower",
    nameAr: "أمريكان تاور",
    nameEn: "American Tower",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 301,
    ticker: "EQIX",
    slug: "equinix",
    nameAr: "إكوينكس",
    nameEn: "Equinix Inc.",
    sector: "عقارات",
    exchange: "NASDAQ",
  },
  {
    id: 302,
    ticker: "SPG",
    slug: "simon-property",
    nameAr: "مجموعة سايمون",
    nameEn: "Simon Property Group",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 303,
    ticker: "O",
    slug: "realty-income",
    nameAr: "ريالتي إنكام",
    nameEn: "Realty Income",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 304,
    ticker: "PSA",
    slug: "public-storage",
    nameAr: "بابليك ستوريدج",
    nameEn: "Public Storage",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 305,
    ticker: "VICI",
    slug: "vici-properties",
    nameAr: "فيتشي بروبرتيز",
    nameEn: "VICI Properties",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 306,
    ticker: "WELL",
    slug: "welltower",
    nameAr: "ويلتاور",
    nameEn: "Welltower Inc.",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 307,
    ticker: "DLR",
    slug: "digital-realty",
    nameAr: "ديجيتال ريالتي",
    nameEn: "Digital Realty Trust",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 308,
    ticker: "AVB",
    slug: "avalonbay",
    nameAr: "أفالون باي",
    nameEn: "AvalonBay Communities",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 309,
    ticker: "EQR",
    slug: "equity-residential",
    nameAr: "إكويتي ريزيدنشيال",
    nameEn: "Equity Residential",
    sector: "عقارات",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🎓 تكنولوجيا التعليم
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 310,
    ticker: "DUOL",
    slug: "duolingo",
    nameAr: "دولينجو",
    nameEn: "Duolingo Inc.",
    sector: "تكنولوجيا التعليم",
    exchange: "NASDAQ",
  },
  {
    id: 311,
    ticker: "COUR",
    slug: "coursera",
    nameAr: "كورسيرا",
    nameEn: "Coursera Inc.",
    sector: "تكنولوجيا التعليم",
    exchange: "NYSE",
  },
  {
    id: 312,
    ticker: "CHGG",
    slug: "chegg",
    nameAr: "شيج",
    nameEn: "Chegg Inc.",
    sector: "تكنولوجيا التعليم",
    exchange: "NYSE",
  },
  {
    id: 313,
    ticker: "TAL",
    slug: "tal-education",
    nameAr: "تال للتعليم الصيني",
    nameEn: "TAL Education Group",
    sector: "تكنولوجيا التعليم",
    exchange: "NYSE",
  },
  {
    id: 314,
    ticker: "EDU",
    slug: "new-oriental",
    nameAr: "نيو أورينتال الصيني",
    nameEn: "New Oriental Education",
    sector: "تكنولوجيا التعليم",
    exchange: "NYSE",
  },
  {
    id: 315,
    ticker: "UDMY",
    slug: "udemy",
    nameAr: "يوديمي",
    nameEn: "Udemy Inc.",
    sector: "تكنولوجيا التعليم",
    exchange: "NASDAQ",
  },
];
