export const WORLD_STOCKS_CONFIG = [
  // ── تكنولوجيا أمريكية ─────────────────────────────────────────────────────
  {
    id: 1,
    ticker: "AAPL",
    slug: "apple",
    nameAr: "آبل",
    nameEn: "Apple Inc.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 2,
    ticker: "MSFT",
    slug: "microsoft",
    nameAr: "مايكروسوفت",
    nameEn: "Microsoft Corp.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 3,
    ticker: "NVDA",
    slug: "nvidia",
    nameAr: "إنفيديا",
    nameEn: "NVIDIA Corp.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 4,
    ticker: "GOOGL",
    slug: "google",
    nameAr: "ألفابيت جوجل",
    nameEn: "Alphabet Inc.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 5,
    ticker: "META",
    slug: "meta",
    nameAr: "ميتا",
    nameEn: "Meta Platforms",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 6,
    ticker: "AMZN",
    slug: "amazon",
    nameAr: "أمازون",
    nameEn: "Amazon.com Inc.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 7,
    ticker: "TSLA",
    slug: "tesla",
    nameAr: "تسلا",
    nameEn: "Tesla Inc.",
    sector: "سيارات",
    exchange: "NASDAQ",
  },
  {
    id: 8,
    ticker: "ORCL",
    slug: "oracle",
    nameAr: "أوراكل",
    nameEn: "Oracle Corp.",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 9,
    ticker: "CRM",
    slug: "salesforce",
    nameAr: "سيلزفورس",
    nameEn: "Salesforce Inc.",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 10,
    ticker: "INTC",
    slug: "intel",
    nameAr: "إنتل",
    nameEn: "Intel Corp.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 11,
    ticker: "AMD",
    slug: "amd",
    nameAr: "AMD",
    nameEn: "Advanced Micro Devices",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 12,
    ticker: "NFLX",
    slug: "netflix",
    nameAr: "نتفليكس",
    nameEn: "Netflix Inc.",
    sector: "إعلام",
    exchange: "NASDAQ",
  },
  {
    id: 13,
    ticker: "ADBE",
    slug: "adobe",
    nameAr: "أدوبي",
    nameEn: "Adobe Inc.",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },

  // ── مالية وبنوك ──────────────────────────────────────────────────────────
  {
    id: 14,
    ticker: "JPM",
    slug: "jpmorgan",
    nameAr: "جي بي مورغان",
    nameEn: "JPMorgan Chase",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 15,
    ticker: "BAC",
    slug: "bofa",
    nameAr: "بنك أوف أمريكا",
    nameEn: "Bank of America",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 16,
    ticker: "GS",
    slug: "goldman",
    nameAr: "جولدمان ساكس",
    nameEn: "Goldman Sachs",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 17,
    ticker: "V",
    slug: "visa",
    nameAr: "فيزا",
    nameEn: "Visa Inc.",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 18,
    ticker: "MA",
    slug: "mastercard",
    nameAr: "ماستركارد",
    nameEn: "Mastercard Inc.",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 19,
    ticker: "MS",
    slug: "morgan-stanley",
    nameAr: "مورغان ستانلي",
    nameEn: "Morgan Stanley",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 20,
    ticker: "AXP",
    slug: "american-express",
    nameAr: "أمريكان إكسبريس",
    nameEn: "American Express",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 21,
    ticker: "C",
    slug: "citigroup",
    nameAr: "سيتي جروب",
    nameEn: "Citigroup Inc.",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 22,
    ticker: "BLK",
    slug: "blackrock",
    nameAr: "بلاك روك",
    nameEn: "BlackRock Inc.",
    sector: "مالية",
    exchange: "NYSE",
  },
  {
    id: 23,
    ticker: "WFC",
    slug: "wells-fargo",
    nameAr: "ويلز فارجو",
    nameEn: "Wells Fargo",
    sector: "مالية",
    exchange: "NYSE",
  },

  // ── طاقة ونفط ────────────────────────────────────────────────────────────
  {
    id: 24,
    ticker: "XOM",
    slug: "exxon",
    nameAr: "إكسون موبيل",
    nameEn: "Exxon Mobil Corp.",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 25,
    ticker: "CVX",
    slug: "chevron",
    nameAr: "شيفرون",
    nameEn: "Chevron Corp.",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 26,
    ticker: "2222.SR",
    slug: "aramco",
    nameAr: "أرامكو السعودية",
    nameEn: "Saudi Aramco",
    sector: "طاقة",
    exchange: "Tadawul",
  },
  {
    id: 27,
    ticker: "SHEL",
    slug: "shell",
    nameAr: "شيل",
    nameEn: "Shell plc",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 28,
    ticker: "TTE",
    slug: "totalenergies",
    nameAr: "توتال إنرجيز",
    nameEn: "TotalEnergies",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 29,
    ticker: "BP",
    slug: "bp",
    nameAr: "بي بي",
    nameEn: "BP plc",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 30,
    ticker: "COP",
    slug: "conocophillips",
    nameAr: "كونوكو فيليبس",
    nameEn: "ConocoPhillips",
    sector: "طاقة",
    exchange: "NYSE",
  },
  {
    id: 31,
    ticker: "SLB",
    slug: "schlumberger",
    nameAr: "شلمبرجير",
    nameEn: "Schlumberger",
    sector: "طاقة",
    exchange: "NYSE",
  },

  // ── رعاية صحية وصيدلة ────────────────────────────────────────────────────
  {
    id: 32,
    ticker: "JNJ",
    slug: "jnj",
    nameAr: "جونسون آند جونسون",
    nameEn: "Johnson & Johnson",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 33,
    ticker: "UNH",
    slug: "unitedhealth",
    nameAr: "يونايتد هيلث",
    nameEn: "UnitedHealth Group",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 34,
    ticker: "PFE",
    slug: "pfizer",
    nameAr: "فايزر",
    nameEn: "Pfizer Inc.",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 35,
    ticker: "LLY",
    slug: "eli-lilly",
    nameAr: "إيلي ليلي",
    nameEn: "Eli Lilly and Co.",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 36,
    ticker: "NVO",
    slug: "novo-nordisk",
    nameAr: "نوفو نورديسك",
    nameEn: "Novo Nordisk",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 37,
    ticker: "ABBV",
    slug: "abbvie",
    nameAr: "آبفي",
    nameEn: "AbbVie Inc.",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 38,
    ticker: "MRK",
    slug: "merck",
    nameAr: "ميرك",
    nameEn: "Merck & Co.",
    sector: "صحة",
    exchange: "NYSE",
  },
  {
    id: 39,
    ticker: "TMO",
    slug: "thermo-fisher",
    nameAr: "ثيرمو فيشر",
    nameEn: "Thermo Fisher",
    sector: "صحة",
    exchange: "NYSE",
  },

  // ── استهلاك أساسي ومطاعم ─────────────────────────────────────────────────
  {
    id: 40,
    ticker: "WMT",
    slug: "walmart",
    nameAr: "وول مارت",
    nameEn: "Walmart Inc.",
    sector: "استهلاك",
    exchange: "NYSE",
  },
  {
    id: 41,
    ticker: "MCD",
    slug: "mcdonalds",
    nameAr: "ماكدونالدز",
    nameEn: "McDonald's Corp.",
    sector: "مطاعم",
    exchange: "NYSE",
  },
  {
    id: 42,
    ticker: "KO",
    slug: "coca-cola",
    nameAr: "كوكا كولا",
    nameEn: "Coca-Cola Co.",
    sector: "استهلاك",
    exchange: "NYSE",
  },
  {
    id: 43,
    ticker: "PEP",
    slug: "pepsico",
    nameAr: "بيبسيكو",
    nameEn: "PepsiCo Inc.",
    sector: "استهلاك",
    exchange: "NASDAQ",
  },
  {
    id: 44,
    ticker: "PG",
    slug: "procter-gamble",
    nameAr: "بروكتر آند جامبل",
    nameEn: "Procter & Gamble",
    sector: "استهلاك",
    exchange: "NYSE",
  },
  {
    id: 45,
    ticker: "COST",
    slug: "costco",
    nameAr: "كوستكو",
    nameEn: "Costco Wholesale",
    sector: "استهلاك",
    exchange: "NASDAQ",
  },
  {
    id: 46,
    ticker: "TGT",
    slug: "target",
    nameAr: "تارجت",
    nameEn: "Target Corp.",
    sector: "استهلاك",
    exchange: "NYSE",
  },
  {
    id: 47,
    ticker: "SBUX",
    slug: "starbucks",
    nameAr: "ستاربكس",
    nameEn: "Starbucks Corp.",
    sector: "مطاعم",
    exchange: "NASDAQ",
  },
  {
    id: 48,
    ticker: "NKE",
    slug: "nike",
    nameAr: "نايكي",
    nameEn: "NIKE Inc.",
    sector: "استهلاك",
    exchange: "NYSE",
  },

  // ── أوروبا وآسيا وأشباه الموصلات المتقدمة ────────────────────────────────
  {
    id: 49,
    ticker: "ASML",
    slug: "asml",
    nameAr: "ASML",
    nameEn: "ASML Holding",
    sector: "تكنولوجيا",
    exchange: "NASDAQ",
  },
  {
    id: 50,
    ticker: "TSM",
    slug: "tsmc",
    nameAr: "TSMC تايوان",
    nameEn: "Taiwan Semiconductor",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 51,
    ticker: "SONY",
    slug: "sony",
    nameAr: "سوني",
    nameEn: "Sony Group Corp.",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 52,
    ticker: "SAP",
    slug: "sap",
    nameAr: "SAP الألمانية",
    nameEn: "SAP SE",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 53,
    ticker: "BABA",
    slug: "alibaba",
    nameAr: "علي بابا",
    nameEn: "Alibaba Group",
    sector: "تكنولوجيا",
    exchange: "NYSE",
  },
  {
    id: 54,
    ticker: "9988.HK",
    slug: "alibaba-hk",
    nameAr: "علي بابا هونغ كونغ",
    nameEn: "Alibaba HK",
    sector: "تكنولوجيا",
    exchange: "HKEX",
  },
  {
    id: 55,
    ticker: "005930.KS",
    slug: "samsung",
    nameAr: "سامسونج",
    nameEn: "Samsung Electronics",
    sector: "تكنولوجيا",
    exchange: "KRX",
  },
  {
    id: 56,
    ticker: "QCOM",
    slug: "qualcomm",
    nameAr: "كوالكوم",
    nameEn: "Qualcomm Inc.",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 57,
    ticker: "TXN",
    slug: "texas-instruments",
    nameAr: "تكساس إنسترومنتس",
    nameEn: "Texas Instruments",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 58,
    ticker: "AMAT",
    slug: "applied-materials",
    nameAr: "أبلايد ماتيريالز",
    nameEn: "Applied Materials",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 59,
    ticker: "MU",
    slug: "micron",
    nameAr: "مايكرون",
    nameEn: "Micron Technology",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },
  {
    id: 60,
    ticker: "ARM",
    slug: "arm-holdings",
    nameAr: "آرم",
    nameEn: "Arm Holdings",
    sector: "أشباه موصلات",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🤖 ذكاء اصطناعي
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 61,
    ticker: "PLTR",
    slug: "palantir",
    nameAr: "بالانتير",
    nameEn: "Palantir Technologies",
    sector: "ذكاء اصطناعي",
    exchange: "NASDAQ",
  },
  {
    id: 62,
    ticker: "CRWV",
    slug: "coreweave",
    nameAr: "كور ويف",
    nameEn: "CoreWeave Inc.",
    sector: "ذكاء اصطناعي",
    exchange: "NASDAQ",
  },
  {
    id: 63,
    ticker: "AI",
    slug: "c3ai",
    nameAr: "سي3 للذكاء",
    nameEn: "C3.ai Inc.",
    sector: "ذكاء اصطناعي",
    exchange: "NYSE",
  },
  {
    id: 64,
    ticker: "PATH",
    slug: "uipath",
    nameAr: "يو آي باث",
    nameEn: "UiPath Inc.",
    sector: "ذكاء اصطناعي",
    exchange: "NYSE",
  },
  {
    id: 65,
    ticker: "SNOW",
    slug: "snowflake",
    nameAr: "سنوفليك",
    nameEn: "Snowflake Inc.",
    sector: "ذكاء اصطناعي",
    exchange: "NYSE",
  },
  {
    id: 66,
    ticker: "SMCI",
    slug: "supermicro",
    nameAr: "سوبر مايكرو",
    nameEn: "Super Micro Computer",
    sector: "ذكاء اصطناعي",
    exchange: "NASDAQ",
  },
  {
    id: 67,
    ticker: "AVGO",
    slug: "broadcom",
    nameAr: "برودكوم",
    nameEn: "Broadcom Inc.",
    sector: "ذكاء اصطناعي",
    exchange: "NASDAQ",
  },
  {
    id: 68,
    ticker: "MRVL",
    slug: "marvell",
    nameAr: "مارفيل تكنولوجي",
    nameEn: "Marvell Technology",
    sector: "ذكاء اصطناعي",
    exchange: "NASDAQ",
  },
  {
    id: 69,
    ticker: "NBIS",
    slug: "nebius",
    nameAr: "نيبيوس",
    nameEn: "Nebius Group",
    sector: "ذكاء اصطناعي",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🔒 أمن سيبراني
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 70,
    ticker: "CRWD",
    slug: "crowdstrike",
    nameAr: "كراود سترايك",
    nameEn: "CrowdStrike Holdings",
    sector: "أمن سيبراني",
    exchange: "NASDAQ",
  },
  {
    id: 71,
    ticker: "PANW",
    slug: "paloalto",
    nameAr: "بالو ألتو نتووركس",
    nameEn: "Palo Alto Networks",
    sector: "أمن سيبراني",
    exchange: "NASDAQ",
  },
  {
    id: 72,
    ticker: "NET",
    slug: "cloudflare",
    nameAr: "كلاود فلير",
    nameEn: "Cloudflare Inc.",
    sector: "أمن سيبراني",
    exchange: "NYSE",
  },
  {
    id: 73,
    ticker: "ZS",
    slug: "zscaler",
    nameAr: "زي سكيلر",
    nameEn: "Zscaler Inc.",
    sector: "أمن سيبراني",
    exchange: "NASDAQ",
  },
  {
    id: 74,
    ticker: "S",
    slug: "sentinelone",
    nameAr: "سنتينل ون",
    nameEn: "SentinelOne Inc.",
    sector: "أمن سيبراني",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ☁️ سحابة وبرمجيات
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 75,
    ticker: "NOW",
    slug: "servicenow",
    nameAr: "سيرفيس ناو",
    nameEn: "ServiceNow Inc.",
    sector: "برمجيات",
    exchange: "NYSE",
  },
  {
    id: 76,
    ticker: "WDAY",
    slug: "workday",
    nameAr: "ووركداي",
    nameEn: "Workday Inc.",
    sector: "برمجيات",
    exchange: "NASDAQ",
  },
  {
    id: 77,
    ticker: "TEAM",
    slug: "atlassian",
    nameAr: "أتلاسيان",
    nameEn: "Atlassian Corp.",
    sector: "برمجيات",
    exchange: "NASDAQ",
  },
  {
    id: 78,
    ticker: "ZM",
    slug: "zoom",
    nameAr: "زووم",
    nameEn: "Zoom Video Comm.",
    sector: "برمجيات",
    exchange: "NASDAQ",
  },
  {
    id: 79,
    ticker: "DDOG",
    slug: "datadog",
    nameAr: "داتا دوج",
    nameEn: "Datadog Inc.",
    sector: "برمجيات",
    exchange: "NASDAQ",
  },
  {
    id: 80,
    ticker: "MDB",
    slug: "mongodb",
    nameAr: "مونغو دي بي",
    nameEn: "MongoDB Inc.",
    sector: "برمجيات",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🚗 سيارات تقليدية وكهربائية
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 81,
    ticker: "TM",
    slug: "toyota",
    nameAr: "تويوتا",
    nameEn: "Toyota Motor",
    sector: "سيارات",
    exchange: "NYSE",
  },
  {
    id: 82,
    ticker: "F",
    slug: "ford",
    nameAr: "فورد",
    nameEn: "Ford Motor Co.",
    sector: "سيارات",
    exchange: "NYSE",
  },
  {
    id: 83,
    ticker: "GM",
    slug: "general-motors",
    nameAr: "جنرال موتورز",
    nameEn: "General Motors",
    sector: "سيارات",
    exchange: "NYSE",
  },
  {
    id: 84,
    ticker: "RACE",
    slug: "ferrari",
    nameAr: "فيراري",
    nameEn: "Ferrari N.V.",
    sector: "سيارات",
    exchange: "NYSE",
  },
  {
    id: 85,
    ticker: "STLA",
    slug: "stellantis",
    nameAr: "ستيلانتس",
    nameEn: "Stellantis N.V.",
    sector: "سيارات",
    exchange: "NYSE",
  },
  {
    id: 86,
    ticker: "RIVN",
    slug: "rivian",
    nameAr: "ريفيان",
    nameEn: "Rivian Automotive",
    sector: "سيارات كهربائية",
    exchange: "NASDAQ",
  },
  {
    id: 87,
    ticker: "NIO",
    slug: "nio",
    nameAr: "نيو الصينية",
    nameEn: "NIO Inc.",
    sector: "سيارات كهربائية",
    exchange: "NYSE",
  },
  {
    id: 88,
    ticker: "LCID",
    slug: "lucid",
    nameAr: "لوسيد موتورز",
    nameEn: "Lucid Group Inc.",
    sector: "سيارات كهربائية",
    exchange: "NASDAQ",
  },
  {
    id: 89,
    ticker: "LI",
    slug: "li-auto",
    nameAr: "لي أوتو الصينية",
    nameEn: "Li Auto Inc.",
    sector: "سيارات كهربائية",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ✈️ فضاء وطيران ودفاع
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 90,
    ticker: "LMT",
    slug: "lockheed",
    nameAr: "لوكهيد مارتن",
    nameEn: "Lockheed Martin",
    sector: "دفاع وفضاء",
    exchange: "NYSE",
  },
  {
    id: 91,
    ticker: "RTX",
    slug: "rtx",
    nameAr: "RTX كورب",
    nameEn: "RTX Corp.",
    sector: "دفاع وفضاء",
    exchange: "NYSE",
  },
  {
    id: 92,
    ticker: "BA",
    slug: "boeing",
    nameAr: "بوينج",
    nameEn: "Boeing Co.",
    sector: "دفاع وفضاء",
    exchange: "NYSE",
  },
  {
    id: 93,
    ticker: "RKLB",
    slug: "rocketlab",
    nameAr: "روكيت لاب",
    nameEn: "Rocket Lab USA",
    sector: "دفاع وفضاء",
    exchange: "NASDAQ",
  },
  {
    id: 94,
    ticker: "JOBY",
    slug: "joby",
    nameAr: "جوبي أفيشن",
    nameEn: "Joby Aviation",
    sector: "دفاع وفضاء",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 💳 فينتك وعملات رقمية
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 95,
    ticker: "COIN",
    slug: "coinbase",
    nameAr: "كوينبيس",
    nameEn: "Coinbase Global",
    sector: "فينتك وكريبتو",
    exchange: "NASDAQ",
  },
  {
    id: 96,
    ticker: "MSTR",
    slug: "microstrategy",
    nameAr: "مايكرو ستراتيجي",
    nameEn: "MicroStrategy Inc.",
    sector: "فينتك وكريبتو",
    exchange: "NASDAQ",
  },
  {
    id: 97,
    ticker: "PYPL",
    slug: "paypal",
    nameAr: "باي بال",
    nameEn: "PayPal Holdings",
    sector: "فينتك وكريبتو",
    exchange: "NASDAQ",
  },
  {
    id: 98,
    ticker: "SQ",
    slug: "block",
    nameAr: "بلوك (سكوير)",
    nameEn: "Block Inc.",
    sector: "فينتك وكريبتو",
    exchange: "NYSE",
  }, // Corrected ticker from XYZ to SQ
  {
    id: 99,
    ticker: "SOFI",
    slug: "sofi",
    nameAr: "سوفاي تكنولوجيز",
    nameEn: "SoFi Technologies",
    sector: "فينتك وكريبتو",
    exchange: "NASDAQ",
  },
  {
    id: 100,
    ticker: "HOOD",
    slug: "robinhood",
    nameAr: "روبين هود",
    nameEn: "Robinhood Markets",
    sector: "فينتك وكريبتو",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🛒 تجارة إلكترونية
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 101,
    ticker: "SHOP",
    slug: "shopify",
    nameAr: "شوبيفاي",
    nameEn: "Shopify Inc.",
    sector: "تجارة إلكترونية",
    exchange: "NYSE",
  },
  {
    id: 102,
    ticker: "MELI",
    slug: "mercadolibre",
    nameAr: "ميركادو ليبري",
    nameEn: "MercadoLibre Inc.",
    sector: "تجارة إلكترونية",
    exchange: "NASDAQ",
  },
  {
    id: 103,
    ticker: "SE",
    slug: "sea-limited",
    nameAr: "سي ليميتد",
    nameEn: "Sea Limited",
    sector: "تجارة إلكترونية",
    exchange: "NYSE",
  },
  {
    id: 104,
    ticker: "PDD",
    slug: "pinduoduo",
    nameAr: "بيندودو / تيمو",
    nameEn: "PDD Holdings",
    sector: "تجارة إلكترونية",
    exchange: "NASDAQ",
  },
  {
    id: 105,
    ticker: "EBAY",
    slug: "ebay",
    nameAr: "إيباي",
    nameEn: "eBay Inc.",
    sector: "تجارة إلكترونية",
    exchange: "NASDAQ",
  },
  {
    id: 106,
    ticker: "CPNG",
    slug: "coupang",
    nameAr: "كوبانغ",
    nameEn: "Coupang Inc.",
    sector: "تجارة إلكترونية",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 📱 تواصل اجتماعي وترفيه
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 107,
    ticker: "SNAP",
    slug: "snapchat",
    nameAr: "سناب شات",
    nameEn: "Snap Inc.",
    sector: "وسائل التواصل",
    exchange: "NYSE",
  },
  {
    id: 108,
    ticker: "PINS",
    slug: "pinterest",
    nameAr: "بينتريست",
    nameEn: "Pinterest Inc.",
    sector: "وسائل التواصل",
    exchange: "NYSE",
  },
  {
    id: 109,
    ticker: "RDDT",
    slug: "reddit",
    nameAr: "ريديت",
    nameEn: "Reddit Inc.",
    sector: "وسائل التواصل",
    exchange: "NYSE",
  },
  {
    id: 110,
    ticker: "SPOT",
    slug: "spotify",
    nameAr: "سبوتيفاي",
    nameEn: "Spotify Technology",
    sector: "وسائل التواصل",
    exchange: "NYSE",
  },
  {
    id: 111,
    ticker: "RBLX",
    slug: "roblox",
    nameAr: "روبلوكس",
    nameEn: "Roblox Corp.",
    sector: "ألعاب",
    exchange: "NYSE",
  },
  {
    id: 112,
    ticker: "EA",
    slug: "ea-games",
    nameAr: "إليكترونيك آرتس",
    nameEn: "Electronic Arts",
    sector: "ألعاب",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🚕 تنقل ولوجستيات واقتصاد مشاركة
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 113,
    ticker: "UBER",
    slug: "uber",
    nameAr: "أوبر",
    nameEn: "Uber Technologies",
    sector: "تنقل وسفر",
    exchange: "NYSE",
  },
  {
    id: 114,
    ticker: "LYFT",
    slug: "lyft",
    nameAr: "ليفت",
    nameEn: "Lyft Inc.",
    sector: "تنقل وسفر",
    exchange: "NASDAQ",
  },
  {
    id: 115,
    ticker: "ABNB",
    slug: "airbnb",
    nameAr: "إير بي إن بي",
    nameEn: "Airbnb Inc.",
    sector: "تنقل وسفر",
    exchange: "NASDAQ",
  },
  {
    id: 116,
    ticker: "BKNG",
    slug: "booking",
    nameAr: "بوكينج هولدينغز",
    nameEn: "Booking Holdings",
    sector: "تنقل وسفر",
    exchange: "NASDAQ",
  },
  {
    id: 117,
    ticker: "UPS",
    slug: "ups",
    nameAr: "يو بي إس",
    nameEn: "United Parcel Service",
    sector: "نقل ولوجستيات",
    exchange: "NYSE",
  },
  {
    id: 118,
    ticker: "FDX",
    slug: "fedex",
    nameAr: "فيديكس",
    nameEn: "FedEx Corp.",
    sector: "نقل ولوجستيات",
    exchange: "NYSE",
  },
  {
    id: 119,
    ticker: "UNP",
    slug: "union-pacific",
    nameAr: "يونيون باسيفيك",
    nameEn: "Union Pacific",
    sector: "نقل ولوجستيات",
    exchange: "NYSE",
  },
  {
    id: 120,
    ticker: "DAL",
    slug: "delta",
    nameAr: "خطوط دلتا",
    nameEn: "Delta Air Lines",
    sector: "تنقل وسفر",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 📡 اتصالات
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 121,
    ticker: "T",
    slug: "att",
    nameAr: "AT&T",
    nameEn: "AT&T Inc.",
    sector: "اتصالات",
    exchange: "NYSE",
  },
  {
    id: 122,
    ticker: "VZ",
    slug: "verizon",
    nameAr: "فيريزون",
    nameEn: "Verizon Comm.",
    sector: "اتصالات",
    exchange: "NYSE",
  },
  {
    id: 123,
    ticker: "TMUS",
    slug: "tmobile",
    nameAr: "تي-موبايل",
    nameEn: "T-Mobile US",
    sector: "اتصالات",
    exchange: "NASDAQ",
  },
  {
    id: 124,
    ticker: "VOD",
    slug: "vodafone",
    nameAr: "فودافون",
    nameEn: "Vodafone Group",
    sector: "اتصالات",
    exchange: "NASDAQ",
  },
  {
    id: 125,
    ticker: "CMCSA",
    slug: "comcast",
    nameAr: "كومكاست",
    nameEn: "Comcast Corp.",
    sector: "اتصالات",
    exchange: "NASDAQ",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ⚡ طاقة متجددة ومرافق عامة
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 126,
    ticker: "ENPH",
    slug: "enphase",
    nameAr: "إنفيز إنيرجي",
    nameEn: "Enphase Energy",
    sector: "طاقة متجددة",
    exchange: "NASDAQ",
  },
  {
    id: 127,
    ticker: "FSLR",
    slug: "firstsolar",
    nameAr: "فيرست سولار",
    nameEn: "First Solar Inc.",
    sector: "طاقة متجددة",
    exchange: "NASDAQ",
  },
  {
    id: 128,
    ticker: "NEE",
    slug: "nextera",
    nameAr: "نيكست إيرا إنيرجي",
    nameEn: "NextEra Energy",
    sector: "طاقة متجددة",
    exchange: "NYSE",
  },
  {
    id: 129,
    ticker: "GEV",
    slug: "gevernova",
    nameAr: "GE فيرنوفا",
    nameEn: "GE Vernova Inc.",
    sector: "طاقة متجددة",
    exchange: "NYSE",
  },
  {
    id: 130,
    ticker: "DUK",
    slug: "duke-energy",
    nameAr: "ديوك إنيرجي",
    nameEn: "Duke Energy",
    sector: "مرافق عامة",
    exchange: "NYSE",
  },
  {
    id: 131,
    ticker: "SO",
    slug: "southern-company",
    nameAr: "الشركة الجنوبية",
    nameEn: "Southern Company",
    sector: "مرافق عامة",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🏭 صناعة، تشييد، ومواد أساسية
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 132,
    ticker: "CAT",
    slug: "caterpillar",
    nameAr: "كاتربيلر",
    nameEn: "Caterpillar Inc.",
    sector: "صناعة",
    exchange: "NYSE",
  },
  {
    id: 133,
    ticker: "DE",
    slug: "deere",
    nameAr: "جون ديري",
    nameEn: "Deere & Company",
    sector: "صناعة",
    exchange: "NYSE",
  },
  {
    id: 134,
    ticker: "HON",
    slug: "honeywell",
    nameAr: "هانيويل",
    nameEn: "Honeywell Intl.",
    sector: "صناعة",
    exchange: "NASDAQ",
  },
  {
    id: 135,
    ticker: "LIN",
    slug: "linde",
    nameAr: "ليندي",
    nameEn: "Linde plc",
    sector: "مواد أساسية",
    exchange: "NASDAQ",
  },
  {
    id: 136,
    ticker: "BHP",
    slug: "bhp",
    nameAr: "بي إتش بي",
    nameEn: "BHP Group",
    sector: "تعدين ومواد",
    exchange: "NYSE",
  },
  {
    id: 137,
    ticker: "RIO",
    slug: "rio-tinto",
    nameAr: "ريو تينتو",
    nameEn: "Rio Tinto",
    sector: "تعدين ومواد",
    exchange: "NYSE",
  },
  {
    id: 138,
    ticker: "FCX",
    slug: "freeport",
    nameAr: "فريبورت مكموران",
    nameEn: "Freeport-McMoRan",
    sector: "تعدين ومواد",
    exchange: "NYSE",
  },
  {
    id: 139,
    ticker: "NEM",
    slug: "newmont",
    nameAr: "نيومونت",
    nameEn: "Newmont Corp.",
    sector: "تعدين ومواد",
    exchange: "NYSE",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 🏢 عقارات وصناديق الاستثمار العقاري (REITs)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 140,
    ticker: "PLD",
    slug: "prologis",
    nameAr: "برولوجيس",
    nameEn: "Prologis Inc.",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 141,
    ticker: "AMT",
    slug: "american-tower",
    nameAr: "أمريكان تاور",
    nameEn: "American Tower",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 142,
    ticker: "EQIX",
    slug: "equinix",
    nameAr: "إكوينكس",
    nameEn: "Equinix Inc.",
    sector: "عقارات",
    exchange: "NASDAQ",
  },
  {
    id: 143,
    ticker: "SPG",
    slug: "simon-property",
    nameAr: "مجموعة سايمون",
    nameEn: "Simon Property Group",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 144,
    ticker: "O",
    slug: "realty-income",
    nameAr: "ريالتي إنكام",
    nameEn: "Realty Income",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 145,
    ticker: "PSA",
    slug: "public-storage",
    nameAr: "بابليك ستوريدج",
    nameEn: "Public Storage",
    sector: "عقارات",
    exchange: "NYSE",
  },
  {
    id: 146,
    ticker: "VICI",
    slug: "vici-properties",
    nameAr: "فيتشي بروبرتيز",
    nameEn: "VICI Properties",
    sector: "عقارات",
    exchange: "NYSE",
  },
];
