export const WORLD_INDICES = [
  // ── الولايات المتحدة ───────────────────────────────────────────────────────
  {
    id: 1,
    title: "داو جونز",
    titleEn: "Dow Jones",
    ticker: "^DJI",
    slug: "dow-jones",
    region: "أمريكا",
  },
  {
    id: 2,
    title: "ناسداك",
    titleEn: "NASDAQ",
    ticker: "^IXIC",
    slug: "nasdaq",
    region: "أمريكا",
  },
  {
    id: 3,
    title: "S&P 500",
    titleEn: "S&P 500",
    ticker: "^GSPC",
    slug: "sp500",
    region: "أمريكا",
  },
  {
    id: 4,
    title: "راسل 2000",
    titleEn: "Russell 2000",
    ticker: "^RUT",
    slug: "russell2000",
    region: "أمريكا",
  },
  {
    id: 5,
    title: "VIX مؤشر التقلب",
    titleEn: "CBOE VIX",
    ticker: "^VIX",
    slug: "vix",
    region: "أمريكا",
  },

  // ── أوروبا ────────────────────────────────────────────────────────────────
  {
    id: 6,
    title: "فوتسي 100",
    titleEn: "FTSE 100",
    ticker: "^FTSE",
    slug: "ftse100",
    region: "أوروبا",
  },
  {
    id: 7,
    title: "داكس الألماني",
    titleEn: "DAX",
    ticker: "^GDAXI",
    slug: "dax",
    region: "أوروبا",
  },
  {
    id: 8,
    title: "يورو ستوكس 50",
    titleEn: "Euro Stoxx 50",
    ticker: "^STOXX50E",
    slug: "euro-stoxx",
    region: "أوروبا",
  },
  {
    id: 9,
    title: "كاك 40 الفرنسي",
    titleEn: "CAC 40",
    ticker: "^FCHI",
    slug: "cac40",
    region: "أوروبا",
  },
  {
    id: 10,
    title: "إيبكس 35 الإسباني",
    titleEn: "IBEX 35",
    ticker: "^IBEX",
    slug: "ibex35",
    region: "أوروبا",
  },
  {
    id: 11,
    title: "إس إم آي السويسري",
    titleEn: "SMI",
    ticker: "^SSMI",
    slug: "smi",
    region: "أوروبا",
  },
  {
    id: 12,
    title: "فوتسي إم آي بي",
    titleEn: "FTSE MIB",
    ticker: "FTSEMIB.MI",
    slug: "ftse-mib",
    region: "أوروبا",
  },
  {
    id: 13,
    title: "AEX الهولندي",
    titleEn: "AEX",
    ticker: "^AEX",
    slug: "aex",
    region: "أوروبا",
  },

  // ── آسيا والمحيط الهادئ ───────────────────────────────────────────────────
  {
    id: 14,
    title: "نيكاي الياباني",
    titleEn: "Nikkei 225",
    ticker: "^N225",
    slug: "nikkei",
    region: "آسيا",
  },
  {
    id: 15,
    title: "هانج سنج",
    titleEn: "Hang Seng",
    ticker: "^HSI",
    slug: "hang-seng",
    region: "آسيا",
  },
  {
    id: 16,
    title: "شنغهاي الصيني",
    titleEn: "Shanghai",
    ticker: "000001.SS",
    slug: "shanghai",
    region: "آسيا",
  },
  {
    id: 17,
    title: "كوسبي الكوري",
    titleEn: "KOSPI",
    ticker: "^KS11",
    slug: "kospi",
    region: "آسيا",
  },
  {
    id: 18,
    title: "سينسيكس الهندي",
    titleEn: "BSE SENSEX",
    ticker: "^BSESN",
    slug: "sensex",
    region: "آسيا",
  },
  {
    id: 19,
    title: "نيفتي 50 الهندي",
    titleEn: "NIFTY 50",
    ticker: "^NSEI",
    slug: "nifty50",
    region: "آسيا",
  },
  {
    id: 20,
    title: "تايوان المرجحي",
    titleEn: "TWSE",
    ticker: "^TWII",
    slug: "twse",
    region: "آسيا",
  },
  {
    id: 21,
    title: "ASX 200 أسترالي",
    titleEn: "ASX 200",
    ticker: "^AXJO",
    slug: "asx200",
    region: "آسيا",
  },
  {
    id: 22,
    title: "بورصة ماليزيا",
    titleEn: "FTSE Bursa KLCI",
    ticker: "^KLSE",
    slug: "klse",
    region: "آسيا",
  },
  {
    id: 23,
    title: "IDX إندونيسيا",
    titleEn: "IDX Composite",
    ticker: "^JKSE",
    slug: "idx",
    region: "آسيا",
  },
  {
    id: 24,
    title: "NZX 50 نيوزيلندا",
    titleEn: "NZX 50",
    ticker: "^NZ50",
    slug: "nzx50",
    region: "آسيا",
  },

  // ── الشرق الأوسط وأفريقيا ─────────────────────────────────────────────────
  {
    id: 25,
    title: "تاسي السعودي",
    titleEn: "TASI",
    ticker: "^TASI.SR",
    slug: "tasi",
    region: "الشرق الأوسط",
  },
  {
    id: 26,
    title: "EGX 30 المصري",
    titleEn: "EGX 30",
    ticker: "^CASE30",
    slug: "egx30",
    region: "الشرق الأوسط",
  },
  {
    id: 27,
    title: "تل أبيب TA-125",
    titleEn: "TA-125",
    ticker: "^TA125.TA",
    slug: "ta125",
    region: "الشرق الأوسط",
  },
  {
    id: 28,
    title: "Top 40 جنوب أفريقيا",
    titleEn: "JSE Top 40",
    ticker: "^JN0U.JO",
    slug: "jse-top40",
    region: "أفريقيا",
  },

  // ── أمريكا اللاتينية وكندا ────────────────────────────────────────────────
  {
    id: 29,
    title: "TSX الكندي",
    titleEn: "S&P/TSX Composite",
    ticker: "^GSPTSE",
    slug: "tsx",
    region: "أمريكا",
  },
  {
    id: 30,
    title: "بوفيسبا البرازيلي",
    titleEn: "IBOVESPA",
    ticker: "^BVSP",
    slug: "bovespa",
    region: "أمريكا اللاتينية",
  },
  {
    id: 31,
    title: "IPC المكسيكي",
    titleEn: "IPC Mexico",
    ticker: "^MXX",
    slug: "ipc-mexico",
    region: "أمريكا اللاتينية",
  },
  {
    id: 32,
    title: "IPSA التشيلي",
    titleEn: "S&P IPSA",
    ticker: "^IPSA",
    slug: "ipsa",
    region: "أمريكا اللاتينية",
  },
];
